//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AdmobADWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AdmobAD), typeof(System.Object));
		L.RegFunction("Init", new LuaCSFunction(Init));
		L.RegFunction("ShowBanner", new LuaCSFunction(ShowBanner));
		L.RegFunction("CloseBanner", new LuaCSFunction(CloseBanner));
		L.RegFunction("LoadRewardAD", new LuaCSFunction(LoadRewardAD));
		L.RegFunction("ShowADVideo", new LuaCSFunction(ShowADVideo));
		L.RegFunction("New", new LuaCSFunction(_CreateAdmobAD));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAdmobAD(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				AdmobAD obj = new AdmobAD();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: AdmobAD.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AdmobAD obj = (AdmobAD)ToLua.CheckObject<AdmobAD>(L, 1);
			obj.Init();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowBanner(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AdmobAD obj = (AdmobAD)ToLua.CheckObject<AdmobAD>(L, 1);
			obj.ShowBanner();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CloseBanner(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AdmobAD obj = (AdmobAD)ToLua.CheckObject<AdmobAD>(L, 1);
			obj.CloseBanner();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadRewardAD(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AdmobAD obj = (AdmobAD)ToLua.CheckObject<AdmobAD>(L, 1);
			obj.LoadRewardAD();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowADVideo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AdmobAD obj = (AdmobAD)ToLua.CheckObject<AdmobAD>(L, 1);
			System.Action<bool> arg0 = (System.Action<bool>)ToLua.CheckDelegate<System.Action<bool>>(L, 2);
			obj.ShowADVideo(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

