//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AndroidCallWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(AndroidCall), typeof(System.Object));
		L.RegFunction("SetClassName", new LuaCSFunction(SetClassName));
		L.RegFunction("SetActivity", new LuaCSFunction(SetActivity));
		L.RegFunction("CallStaticMethod", new LuaCSFunction(CallStaticMethod));
		L.RegFunction("CallStaticMethod_S", new LuaCSFunction(CallStaticMethod_S));
		L.RegFunction("CallStaticMethod_s_s", new LuaCSFunction(CallStaticMethod_s_s));
		L.RegFunction("CallMethod", new LuaCSFunction(CallMethod));
		L.RegFunction("CallMethod_Para", new LuaCSFunction(CallMethod_Para));
		L.RegFunction("CallMethod_S", new LuaCSFunction(CallMethod_S));
		L.RegFunction("CallMethod_s_s", new LuaCSFunction(CallMethod_s_s));
		L.RegFunction("New", new LuaCSFunction(_CreateAndroidCall));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateAndroidCall(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				AndroidCall obj = new AndroidCall();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: AndroidCall.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetClassName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AndroidCall obj = (AndroidCall)ToLua.CheckObject<AndroidCall>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetClassName(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetActivity(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			AndroidCall obj = (AndroidCall)ToLua.CheckObject<AndroidCall>(L, 1);
			obj.SetActivity();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CallStaticMethod(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AndroidCall obj = (AndroidCall)ToLua.CheckObject<AndroidCall>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.CallStaticMethod(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CallStaticMethod_S(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			AndroidCall obj = (AndroidCall)ToLua.CheckObject<AndroidCall>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			obj.CallStaticMethod_S(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CallStaticMethod_s_s(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			AndroidCall obj = (AndroidCall)ToLua.CheckObject<AndroidCall>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			obj.CallStaticMethod_s_s(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CallMethod(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			AndroidCall obj = (AndroidCall)ToLua.CheckObject<AndroidCall>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.CallMethod(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CallMethod_Para(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			AndroidCall obj = (AndroidCall)ToLua.CheckObject<AndroidCall>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			object[] arg1 = ToLua.ToParamsObject(L, 3, count - 2);
			obj.CallMethod_Para(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CallMethod_S(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			AndroidCall obj = (AndroidCall)ToLua.CheckObject<AndroidCall>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			obj.CallMethod_S(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CallMethod_s_s(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			AndroidCall obj = (AndroidCall)ToLua.CheckObject<AndroidCall>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			obj.CallMethod_s_s(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

