//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ApplicationKernelWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ApplicationKernel), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("GetApplicationLua", new LuaCSFunction(GetApplicationLua));
		L.RegFunction("GetObjectPoolManager", new LuaCSFunction(GetObjectPoolManager));
		L.RegFunction("GetResManager", new LuaCSFunction(GetResManager));
		L.RegFunction("InitApplicationLua", new LuaCSFunction(InitApplicationLua));
		L.RegFunction("InitResManager", new LuaCSFunction(InitResManager));
		L.RegFunction("CheckExtractResource", new LuaCSFunction(CheckExtractResource));
		L.RegFunction("InitApplication", new LuaCSFunction(InitApplication));
		L.RegFunction("StartLua", new LuaCSFunction(StartLua));
		L.RegFunction("__eq", new LuaCSFunction(op_Equality));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("testScene", new LuaCSFunction(get_testScene), new LuaCSFunction(set_testScene));
		L.RegVar("runtimeBuildVersion", new LuaCSFunction(get_runtimeBuildVersion), new LuaCSFunction(set_runtimeBuildVersion));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetApplicationLua(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			ApplicationLua o = ApplicationKernel.GetApplicationLua();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetObjectPoolManager(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			LuaFramework.ObjectPoolManager o = ApplicationKernel.GetObjectPoolManager();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetResManager(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			GResManager o = ApplicationKernel.GetResManager();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitApplicationLua(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ApplicationKernel obj = (ApplicationKernel)ToLua.CheckObject<ApplicationKernel>(L, 1);
			obj.InitApplicationLua();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitResManager(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ApplicationKernel obj = (ApplicationKernel)ToLua.CheckObject<ApplicationKernel>(L, 1);
			obj.InitResManager();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CheckExtractResource(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ApplicationKernel obj = (ApplicationKernel)ToLua.CheckObject<ApplicationKernel>(L, 1);
			obj.CheckExtractResource();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitApplication(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ApplicationKernel obj = (ApplicationKernel)ToLua.CheckObject<ApplicationKernel>(L, 1);
			obj.InitApplication();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StartLua(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ApplicationKernel obj = (ApplicationKernel)ToLua.CheckObject<ApplicationKernel>(L, 1);
			obj.StartLua();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_testScene(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ApplicationKernel obj = (ApplicationKernel)o;
			string ret = obj.testScene;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index testScene on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_runtimeBuildVersion(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, ApplicationKernel.runtimeBuildVersion);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_testScene(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ApplicationKernel obj = (ApplicationKernel)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.testScene = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index testScene on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_runtimeBuildVersion(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			ApplicationKernel.runtimeBuildVersion = arg0;
			ApplicationKernel.runtimeBuildVersion = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

