//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class HUDSkipContentWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(HUDSkipContent), typeof(HUDBaseContent));
		L.RegFunction("New", new LuaCSFunction(_CreateHUDSkipContent));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateHUDSkipContent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				HUDSkipContent obj = new HUDSkipContent();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: HUDSkipContent.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

