//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LinkImageText_HrefClickEventWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LinkImageText.HrefClickEvent), typeof(UnityEngine.Events.UnityEvent<string>));
		L.RegFunction("New", new LuaCSFunction(_CreateLinkImageText_HrefClickEvent));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLinkImageText_HrefClickEvent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				LinkImageText.HrefClickEvent obj = new LinkImageText.HrefClickEvent();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: LinkImageText.HrefClickEvent.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

