//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LongClickButton_LongClickEventWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LongClickButton.LongClickEvent), typeof(UnityEngine.Events.UnityEvent));
		L.RegFunction("New", new LuaCSFunction(_CreateLongClickButton_LongClickEvent));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLongClickButton_LongClickEvent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				LongClickButton.LongClickEvent obj = new LongClickButton.LongClickEvent();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: LongClickButton.LongClickEvent.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

