//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_AndroidJavaProxyWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.AndroidJavaProxy), typeof(System.Object));
		L.RegFunction("Invoke", new LuaCSFunction(Invoke));
		L.RegFunction("equals", new LuaCSFunction(equals));
		L.RegFunction("hashCode", new LuaCSFunction(hashCode));
		L.RegFunction("toString", new LuaCSFunction(toString));
		L.RegFunction("New", new LuaCSFunction(_CreateUnityEngine_AndroidJavaProxy));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("javaInterface", new LuaCSFunction(get_javaInterface), null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_AndroidJavaProxy(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1 && TypeChecker.CheckTypes<string>(L, 1))
			{
				string arg0 = ToLua.ToString(L, 1);
				UnityEngine.AndroidJavaProxy obj = new UnityEngine.AndroidJavaProxy(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes<UnityEngine.AndroidJavaClass>(L, 1))
			{
				UnityEngine.AndroidJavaClass arg0 = (UnityEngine.AndroidJavaClass)ToLua.ToObject(L, 1);
				UnityEngine.AndroidJavaProxy obj = new UnityEngine.AndroidJavaProxy(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.AndroidJavaProxy.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Invoke(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3 && TypeChecker.CheckTypes<object[]>(L, 3))
			{
				UnityEngine.AndroidJavaProxy obj = (UnityEngine.AndroidJavaProxy)ToLua.CheckObject<UnityEngine.AndroidJavaProxy>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				object[] arg1 = ToLua.ToObjectArray(L, 3);
				UnityEngine.AndroidJavaObject o = obj.Invoke(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes<UnityEngine.AndroidJavaObject[]>(L, 3))
			{
				UnityEngine.AndroidJavaProxy obj = (UnityEngine.AndroidJavaProxy)ToLua.CheckObject<UnityEngine.AndroidJavaProxy>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				UnityEngine.AndroidJavaObject[] arg1 = ToLua.ToObjectArray<UnityEngine.AndroidJavaObject>(L, 3);
				UnityEngine.AndroidJavaObject o = obj.Invoke(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.AndroidJavaProxy.Invoke");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int equals(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.AndroidJavaProxy obj = (UnityEngine.AndroidJavaProxy)ToLua.CheckObject<UnityEngine.AndroidJavaProxy>(L, 1);
			UnityEngine.AndroidJavaObject arg0 = (UnityEngine.AndroidJavaObject)ToLua.CheckObject<UnityEngine.AndroidJavaObject>(L, 2);
			bool o = obj.equals(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int hashCode(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.AndroidJavaProxy obj = (UnityEngine.AndroidJavaProxy)ToLua.CheckObject<UnityEngine.AndroidJavaProxy>(L, 1);
			int o = obj.hashCode();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int toString(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.AndroidJavaProxy obj = (UnityEngine.AndroidJavaProxy)ToLua.CheckObject<UnityEngine.AndroidJavaProxy>(L, 1);
			string o = obj.toString();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_javaInterface(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.AndroidJavaProxy obj = (UnityEngine.AndroidJavaProxy)o;
			UnityEngine.AndroidJavaClass ret = obj.javaInterface;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index javaInterface on a nil value");
		}
	}
}

