//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_AI_NavMeshObstacleShapeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.AI.NavMeshObstacleShape));
		L.RegVar("Capsule", new LuaCSFunction(get_Capsule), null);
		L.RegVar("Box", new LuaCSFunction(get_Box), null);
		L.RegFunction("IntToEnum", new LuaCSFunction(IntToEnum));
		L.EndEnum();
		TypeTraits<UnityEngine.AI.NavMeshObstacleShape>.Check = CheckType;
		StackTraits<UnityEngine.AI.NavMeshObstacleShape>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.AI.NavMeshObstacleShape arg)
	{
		ToLua.Push(L, arg);
	}

	static Type TypeOf_UnityEngine_AI_NavMeshObstacleShape = typeof(UnityEngine.AI.NavMeshObstacleShape);

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(TypeOf_UnityEngine_AI_NavMeshObstacleShape, L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Capsule(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.AI.NavMeshObstacleShape.Capsule);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Box(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.AI.NavMeshObstacleShape.Box);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tointeger(L, 1);
		UnityEngine.AI.NavMeshObstacleShape o = (UnityEngine.AI.NavMeshObstacleShape)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

