//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Playables_DirectorWrapModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.Playables.DirectorWrapMode));
		L.RegVar("Hold", new LuaCSFunction(get_Hold), null);
		L.RegVar("Loop", new LuaCSFunction(get_Loop), null);
		L.RegVar("None", new LuaCSFunction(get_None), null);
		L.RegFunction("IntToEnum", new LuaCSFunction(IntToEnum));
		L.EndEnum();
		TypeTraits<UnityEngine.Playables.DirectorWrapMode>.Check = CheckType;
		StackTraits<UnityEngine.Playables.DirectorWrapMode>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.Playables.DirectorWrapMode arg)
	{
		ToLua.Push(L, arg);
	}

	static Type TypeOf_UnityEngine_Playables_DirectorWrapMode = typeof(UnityEngine.Playables.DirectorWrapMode);

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(TypeOf_UnityEngine_Playables_DirectorWrapMode, L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Hold(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Playables.DirectorWrapMode.Hold);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Loop(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Playables.DirectorWrapMode.Loop);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Playables.DirectorWrapMode.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tointeger(L, 1);
		UnityEngine.Playables.DirectorWrapMode o = (UnityEngine.Playables.DirectorWrapMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

