//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_AndroidJavaObjectWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.AndroidJavaObject), typeof(System.Object));
		L.RegFunction("Dispose", new LuaCSFunction(Dispose));
		L.RegFunction("Call", new LuaCSFunction(Call));
		L.RegFunction("CallStatic", new LuaCSFunction(CallStatic));
		L.RegFunction("GetRawObject", new LuaCSFunction(GetRawObject));
		L.RegFunction("GetRawClass", new LuaCSFunction(GetRawClass));
		L.RegFunction("New", new LuaCSFunction(_CreateUnityEngine_AndroidJavaObject));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_AndroidJavaObject(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<string[]>(L, 2))
			{
				string arg0 = ToLua.CheckString(L, 1);
				string[] arg1 = ToLua.ToStringArray(L, 2);
				UnityEngine.AndroidJavaObject obj = new UnityEngine.AndroidJavaObject(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<UnityEngine.AndroidJavaObject[]>(L, 2))
			{
				string arg0 = ToLua.CheckString(L, 1);
				UnityEngine.AndroidJavaObject[] arg1 = ToLua.ToObjectArray<UnityEngine.AndroidJavaObject>(L, 2);
				UnityEngine.AndroidJavaObject obj = new UnityEngine.AndroidJavaObject(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<UnityEngine.AndroidJavaClass[]>(L, 2))
			{
				string arg0 = ToLua.CheckString(L, 1);
				UnityEngine.AndroidJavaClass[] arg1 = ToLua.ToObjectArray<UnityEngine.AndroidJavaClass>(L, 2);
				UnityEngine.AndroidJavaObject obj = new UnityEngine.AndroidJavaObject(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<UnityEngine.AndroidJavaProxy[]>(L, 2))
			{
				string arg0 = ToLua.CheckString(L, 1);
				UnityEngine.AndroidJavaProxy[] arg1 = ToLua.ToObjectArray<UnityEngine.AndroidJavaProxy>(L, 2);
				UnityEngine.AndroidJavaObject obj = new UnityEngine.AndroidJavaObject(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<UnityEngine.AndroidJavaRunnable[]>(L, 2))
			{
				string arg0 = ToLua.CheckString(L, 1);
				UnityEngine.AndroidJavaRunnable[] arg1 = ToLua.ToObjectArray<UnityEngine.AndroidJavaRunnable>(L, 2);
				UnityEngine.AndroidJavaObject obj = new UnityEngine.AndroidJavaObject(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (TypeChecker.CheckTypes<string>(L, 1) && TypeChecker.CheckParamsType<object>(L, 2, count - 1))
			{
				string arg0 = ToLua.CheckString(L, 1);
				object[] arg1 = ToLua.ToParamsObject(L, 2, count - 1);
				UnityEngine.AndroidJavaObject obj = new UnityEngine.AndroidJavaObject(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.AndroidJavaObject.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.AndroidJavaObject obj = (UnityEngine.AndroidJavaObject)ToLua.CheckObject<UnityEngine.AndroidJavaObject>(L, 1);
			obj.Dispose();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Call(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			UnityEngine.AndroidJavaObject obj = (UnityEngine.AndroidJavaObject)ToLua.CheckObject<UnityEngine.AndroidJavaObject>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			object[] arg1 = ToLua.ToParamsObject(L, 3, count - 2);
			obj.Call(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CallStatic(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			UnityEngine.AndroidJavaObject obj = (UnityEngine.AndroidJavaObject)ToLua.CheckObject<UnityEngine.AndroidJavaObject>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			object[] arg1 = ToLua.ToParamsObject(L, 3, count - 2);
			obj.CallStatic(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetRawObject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.AndroidJavaObject obj = (UnityEngine.AndroidJavaObject)ToLua.CheckObject<UnityEngine.AndroidJavaObject>(L, 1);
			System.IntPtr o = obj.GetRawObject();
			LuaDLL.lua_pushlightuserdata(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetRawClass(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.AndroidJavaObject obj = (UnityEngine.AndroidJavaObject)ToLua.CheckObject<UnityEngine.AndroidJavaObject>(L, 1);
			System.IntPtr o = obj.GetRawClass();
			LuaDLL.lua_pushlightuserdata(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

