//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Video_VideoRenderModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.Video.VideoRenderMode));
		L.RegVar("CameraFarPlane", new LuaCSFunction(get_CameraFarPlane), null);
		L.RegVar("CameraNearPlane", new LuaCSFunction(get_CameraNearPlane), null);
		L.RegVar("RenderTexture", new LuaCSFunction(get_RenderTexture), null);
		L.RegVar("MaterialOverride", new LuaCSFunction(get_MaterialOverride), null);
		L.RegVar("APIOnly", new LuaCSFunction(get_APIOnly), null);
		L.RegFunction("IntToEnum", new LuaCSFunction(IntToEnum));
		L.EndEnum();
		TypeTraits<UnityEngine.Video.VideoRenderMode>.Check = CheckType;
		StackTraits<UnityEngine.Video.VideoRenderMode>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.Video.VideoRenderMode arg)
	{
		ToLua.Push(L, arg);
	}

	static Type TypeOf_UnityEngine_Video_VideoRenderMode = typeof(UnityEngine.Video.VideoRenderMode);

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(TypeOf_UnityEngine_Video_VideoRenderMode, L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CameraFarPlane(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Video.VideoRenderMode.CameraFarPlane);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CameraNearPlane(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Video.VideoRenderMode.CameraNearPlane);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RenderTexture(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Video.VideoRenderMode.RenderTexture);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MaterialOverride(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Video.VideoRenderMode.MaterialOverride);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_APIOnly(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Video.VideoRenderMode.APIOnly);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tointeger(L, 1);
		UnityEngine.Video.VideoRenderMode o = (UnityEngine.Video.VideoRenderMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

