//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_RenderTextureFormatWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.RenderTextureFormat));
		L.RegVar("ARGB32", new LuaCSFunction(get_ARGB32), null);
		L.RegVar("Depth", new LuaCSFunction(get_Depth), null);
		L.RegVar("ARGBHalf", new LuaCSFunction(get_ARGBHalf), null);
		L.RegVar("Shadowmap", new LuaCSFunction(get_Shadowmap), null);
		L.RegVar("RGB565", new LuaCSFunction(get_RGB565), null);
		L.RegVar("ARGB4444", new LuaCSFunction(get_ARGB4444), null);
		L.RegVar("ARGB1555", new LuaCSFunction(get_ARGB1555), null);
		L.RegVar("Default", new LuaCSFunction(get_Default), null);
		L.RegVar("ARGB2101010", new LuaCSFunction(get_ARGB2101010), null);
		L.RegVar("DefaultHDR", new LuaCSFunction(get_DefaultHDR), null);
		L.RegVar("ARGB64", new LuaCSFunction(get_ARGB64), null);
		L.RegVar("ARGBFloat", new LuaCSFunction(get_ARGBFloat), null);
		L.RegVar("RGFloat", new LuaCSFunction(get_RGFloat), null);
		L.RegVar("RGHalf", new LuaCSFunction(get_RGHalf), null);
		L.RegVar("RFloat", new LuaCSFunction(get_RFloat), null);
		L.RegVar("RHalf", new LuaCSFunction(get_RHalf), null);
		L.RegVar("R8", new LuaCSFunction(get_R8), null);
		L.RegVar("ARGBInt", new LuaCSFunction(get_ARGBInt), null);
		L.RegVar("RGInt", new LuaCSFunction(get_RGInt), null);
		L.RegVar("RInt", new LuaCSFunction(get_RInt), null);
		L.RegVar("BGRA32", new LuaCSFunction(get_BGRA32), null);
		L.RegVar("RGB111110Float", new LuaCSFunction(get_RGB111110Float), null);
		L.RegVar("RG32", new LuaCSFunction(get_RG32), null);
		L.RegVar("RGBAUShort", new LuaCSFunction(get_RGBAUShort), null);
		L.RegVar("RG16", new LuaCSFunction(get_RG16), null);
		L.RegVar("BGRA10101010_XR", new LuaCSFunction(get_BGRA10101010_XR), null);
		L.RegVar("BGR101010_XR", new LuaCSFunction(get_BGR101010_XR), null);
		L.RegVar("R16", new LuaCSFunction(get_R16), null);
		L.RegFunction("IntToEnum", new LuaCSFunction(IntToEnum));
		L.EndEnum();
		TypeTraits<UnityEngine.RenderTextureFormat>.Check = CheckType;
		StackTraits<UnityEngine.RenderTextureFormat>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.RenderTextureFormat arg)
	{
		ToLua.Push(L, arg);
	}

	static Type TypeOf_UnityEngine_RenderTextureFormat = typeof(UnityEngine.RenderTextureFormat);

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(TypeOf_UnityEngine_RenderTextureFormat, L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ARGB32(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.ARGB32);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Depth(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.Depth);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ARGBHalf(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.ARGBHalf);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Shadowmap(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.Shadowmap);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RGB565(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.RGB565);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ARGB4444(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.ARGB4444);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ARGB1555(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.ARGB1555);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Default(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.Default);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ARGB2101010(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.ARGB2101010);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DefaultHDR(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.DefaultHDR);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ARGB64(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.ARGB64);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ARGBFloat(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.ARGBFloat);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RGFloat(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.RGFloat);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RGHalf(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.RGHalf);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RFloat(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.RFloat);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RHalf(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.RHalf);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_R8(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.R8);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ARGBInt(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.ARGBInt);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RGInt(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.RGInt);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RInt(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.RInt);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BGRA32(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.BGRA32);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RGB111110Float(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.RGB111110Float);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RG32(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.RG32);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RGBAUShort(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.RGBAUShort);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RG16(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.RG16);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BGRA10101010_XR(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.BGRA10101010_XR);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BGR101010_XR(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.BGR101010_XR);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_R16(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureFormat.R16);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tointeger(L, 1);
		UnityEngine.RenderTextureFormat o = (UnityEngine.RenderTextureFormat)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

