//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_UI_InputField_ContentTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.UI.InputField.ContentType));
		L.RegVar("Standard", new LuaCSFunction(get_Standard), null);
		L.RegVar("Autocorrected", new LuaCSFunction(get_Autocorrected), null);
		L.RegVar("IntegerNumber", new LuaCSFunction(get_IntegerNumber), null);
		L.RegVar("DecimalNumber", new LuaCSFunction(get_DecimalNumber), null);
		L.RegVar("Alphanumeric", new LuaCSFunction(get_Alphanumeric), null);
		L.RegVar("Name", new LuaCSFunction(get_Name), null);
		L.RegVar("EmailAddress", new LuaCSFunction(get_EmailAddress), null);
		L.RegVar("Password", new LuaCSFunction(get_Password), null);
		L.RegVar("Pin", new LuaCSFunction(get_Pin), null);
		L.RegVar("Custom", new LuaCSFunction(get_Custom), null);
		L.RegFunction("IntToEnum", new LuaCSFunction(IntToEnum));
		L.EndEnum();
		TypeTraits<UnityEngine.UI.InputField.ContentType>.Check = CheckType;
		StackTraits<UnityEngine.UI.InputField.ContentType>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.UI.InputField.ContentType arg)
	{
		ToLua.Push(L, arg);
	}

	static Type TypeOf_UnityEngine_UI_InputField_ContentType = typeof(UnityEngine.UI.InputField.ContentType);

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(TypeOf_UnityEngine_UI_InputField_ContentType, L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Standard(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.InputField.ContentType.Standard);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Autocorrected(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.InputField.ContentType.Autocorrected);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IntegerNumber(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.InputField.ContentType.IntegerNumber);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DecimalNumber(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.InputField.ContentType.DecimalNumber);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Alphanumeric(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.InputField.ContentType.Alphanumeric);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Name(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.InputField.ContentType.Name);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EmailAddress(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.InputField.ContentType.EmailAddress);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Password(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.InputField.ContentType.Password);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Pin(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.InputField.ContentType.Pin);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Custom(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.InputField.ContentType.Custom);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tointeger(L, 1);
		UnityEngine.UI.InputField.ContentType o = (UnityEngine.UI.InputField.ContentType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

