package com.imop.lj.gameserver.wizardraid.msg;

import java.util.HashMap;
import java.util.Map;

import com.imop.lj.core.msg.MessageType;
import com.imop.lj.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class WizardraidMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_WIZARDRAID_ENTER_SINGLE, CGWizardraidEnterSingle.class);
		map.put(MessageType.CG_WIZARDRAID_ASK_ENTER_TEAM, CGWizardraidAskEnterTeam.class);
		map.put(MessageType.CG_WIZARDRAID_ANSWER_ENTER_TEAM, CGWizardraidAnswerEnterTeam.class);
		map.put(MessageType.CG_WIZARDRAID_LEAVE, CGWizardraidLeave.class);
		return map;
	}

}
