using UnityEngine;
using System;

namespace BetaFramework
{
    public class GameCodeGenConstants
    {
        public static string FullRootDir = "Scripts/GenData";
		public static string ClassFileNameFormat = "{0}.cs";
		public static string StaticKeysFileName =  "GDEItemKeys.cs";
		public static string DataClassNameFormat = "{0}Data";
        public static string ContainerDataClassNameFormat = "{0}Container";


        public static string AutoGenMsg = @"// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Excel Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------";

		public static string StaticKeyClassHeader = @"using UnityEngine;
using System;

namespace BetaFramework
{
    public class GDEItemKeys
    {";

        public static string DataClassHeader = @"using UnityEngine;
using System;
using System.Collections.Generic;
using BetaFramework;";

        public static string ClassDeclarationFormat = @"public class {0} : TableSOBaseData<{1}>";
        public static string ContainerClassDeclarationFormat= @"public class {0} : TableSOContainer<{1}, {2}>";
        public static string ClassConstructorsFormat = @"public {0}(string key) : base(key) {{}}
";

        public static string LoadDictMethod = @"public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				return;
			else
			{";

		public static string LoadDictMethodEnd = @"}
		}";

        public static string VariableComments = "//{0}";

        public static string VariableFormat = "public {0} {1};";
        public static string VariableGetSet = " { get; set;}";


        public static string LoadVariableFormat = @"dict.TryGet{0}({1}Key, out _{1});";

		public static string LoadVariableListFormat = @"dict.TryGet{0}List({1}Key, out {1});";

		public static string StaticKeyFormat = "public static string {0}_{1} = \"{1}\";";

		public static string OneDListVariableFormat = @"static string {1}Key = ""{1}"";
		public List<{0}>      {1};";

        public static string TempStringKeyDeclaration = "string customDataKey;";
		public static string LoadCustomVariableFormat = @"dict.TryGetString({1}Key, out customDataKey);
				_{1} = new {0}(customDataKey);";

        public static int IndentLevel1 = 4;
        public static int IndentLevel2 = IndentLevel1 * 2;
        public static int IndentLevel3 = IndentLevel1 * 3;
		public static int IndentLevel4 = IndentLevel1 * 4;
    }
}
