package com.imop.lj.gameserver.onlinegift.msg;

import java.util.HashMap;
import java.util.Map;

import com.imop.lj.core.msg.MessageType;
import com.imop.lj.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class OnlinegiftMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_DALIY_GIFT_LIST_APPLY, CGDaliyGiftListApply.class);
		map.put(MessageType.CG_DALIY_GIFT_PANNEL_APPLY, CGDaliyGiftPannelApply.class);
		map.put(MessageType.CG_DALIY_GIFT_SIGN, CGDaliyGiftSign.class);
		map.put(MessageType.CG_DALIY_GIFT_RETROACTIVE, CGDaliyGiftRetroactive.class);
		map.put(MessageType.CG_GET_ONLINEGIFT_INFO, CGGetOnlinegiftInfo.class);
		map.put(MessageType.CG_RECEIVE_ONLINEGIFT, CGReceiveOnlinegift.class);
		map.put(MessageType.CG_GET_SPEC_ONLINE_GIFT_SHOW_INFO, CGGetSpecOnlineGiftShowInfo.class);
		map.put(MessageType.CG_RECEIVE_SPEC_ONLINE_GIFT, CGReceiveSpecOnlineGift.class);
		return map;
	}

}
