package com.imop.lj.gameserver.human.msg;

import java.util.HashMap;
import java.util.Map;

import com.imop.lj.core.msg.MessageType;
import com.imop.lj.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class HumanMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_KILL_CD_TIME, CGKillCdTime.class);
		map.put(MessageType.CG_ADD_CD, CGAddCd.class);
		map.put(MessageType.CG_FUNC_UPDATE, CGFuncUpdate.class);
		map.put(MessageType.CG_OFFLINEREWARD_INFO, CGOfflinerewardInfo.class);
		map.put(MessageType.CG_OFFLINEREWARD_GET, CGOfflinerewardGet.class);
		map.put(MessageType.CG_BUY_POWER, CGBuyPower.class);
		map.put(MessageType.CG_BUY_POWER_TIPS, CGBuyPowerTips.class);
		map.put(MessageType.CG_CHANNEL_EXCHANGE, CGChannelExchange.class);
		map.put(MessageType.CG_VIP_GET_DAY_REWARD, CGVipGetDayReward.class);
		map.put(MessageType.CG_CHARGE_GM_TEST, CGChargeGmTest.class);
		map.put(MessageType.CG_DAY7_TASK_FINISH, CGDay7TaskFinish.class);
		map.put(MessageType.CG_XIANHU_PANEL, CGXianhuPanel.class);
		map.put(MessageType.CG_XIANHU_OPEN, CGXianhuOpen.class);
		map.put(MessageType.CG_XIANHU_GIVE, CGXianhuGive.class);
		map.put(MessageType.CG_XIANHU_RANK_REWARD, CGXianhuRankReward.class);
		map.put(MessageType.CG_XIANHU_RANK_LIST, CGXianhuRankList.class);
		map.put(MessageType.CG_CURRENCY_EXCHANGE, CGCurrencyExchange.class);
		map.put(MessageType.CG_MONTH_CARD_INFO, CGMonthCardInfo.class);
		map.put(MessageType.CG_BUY_MONTH_CARD, CGBuyMonthCard.class);
		map.put(MessageType.CG_GET_MONTH_CARD_GIFT, CGGetMonthCardGift.class);
		return map;
	}

}
