package com.imop.lj.gameserver.plotdungeon.msg;

import java.util.HashMap;
import java.util.Map;

import com.imop.lj.core.msg.MessageType;
import com.imop.lj.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class PlotdungeonMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_PLOT_DUNGEON_INFO, CGPlotDungeonInfo.class);
		map.put(MessageType.CG_PLOT_DUNGEON_START, CGPlotDungeonStart.class);
		map.put(MessageType.CG_DAILY_PLOT_DUNGEON_INFO, CGDailyPlotDungeonInfo.class);
		map.put(MessageType.CG_GET_DAILY_PLOT_DUNGEON_REWARD, CGGetDailyPlotDungeonReward.class);
		return map;
	}

}
