// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2020-08-20 20:02:00.962
// ------------------------------------------------------------------------------
using System.Collections.Generic;
using UnityEngine;

public class BaseSheet<T> : ScriptableObject
{
    public List<T> dataList = new List<T>();
}