package com.imop.lj.gameserver.lifeskill.msg;

import java.util.HashMap;
import java.util.Map;

import com.imop.lj.core.msg.MessageType;
import com.imop.lj.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class LifeskillMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_LS_MINE_GET_PANNEL, CGLsMineGetPannel.class);
		map.put(MessageType.CG_LS_MINE_START, CGLsMineStart.class);
		map.put(MessageType.CG_LS_MINE_GAIN, CGLsMineGain.class);
		return map;
	}

}
