package com.imop.lj.gameserver.mysteryshop.msg;

import java.util.HashMap;
import java.util.Map;

import com.imop.lj.core.msg.MessageType;
import com.imop.lj.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class MysteryshopMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_REQ_MYSTERY_SHOP_INFO, CGReqMysteryShopInfo.class);
		map.put(MessageType.CG_FLUSH_MYSTERY, CGFlushMystery.class);
		map.put(MessageType.CG_BUY_MS_ITEM, CGBuyMsItem.class);
		return map;
	}

}
