package com.imop.lj.gameserver.nvn.msg;

import java.util.HashMap;
import java.util.Map;

import com.imop.lj.core.msg.MessageType;
import com.imop.lj.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class NvnMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_NVN_ENTER, CGNvnEnter.class);
		map.put(MessageType.CG_NVN_OPEN_PANEL, CGNvnOpenPanel.class);
		map.put(MessageType.CG_NVN_CANCLE_MATCH, CGNvnCancleMatch.class);
		map.put(MessageType.CG_NVN_START_MATCH, CGNvnStartMatch.class);
		map.put(MessageType.CG_NVN_LEAVE, CGNvnLeave.class);
		map.put(MessageType.CG_NVN_RULE, CGNvnRule.class);
		map.put(MessageType.CG_NVN_TOP_RANK_LIST, CGNvnTopRankList.class);
		return map;
	}

}
