// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Excel Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using BetaFramework;

public class AssetBundleData : TableSOBaseData<string>
{
    //资源索引
    public string AssetKey;

    //Bundle名称
    public string BundleName;

    //资源名称
    public string AssetName;

    //资源类型 0-是配置 1-uiprefab
    public int AssetType;
}