// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Excel Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using BetaFramework;

public class ProductConfigContainer : TableSOContainer<string, ProductConfigData>
{
}