// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Excel Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using BetaFramework;

public class ProductConfigData : TableSOBaseData<string>
{
    //内购id
    public string ID;

    //内购类型
    public string ProductType;

    //美元价格
    public string ProductDollarPrice;

    //本地价格
    public string productLocalizedPrice;

    //获得金币数
    public int ProductCoins;
}