// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Excel Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using BetaFramework;

public class UFConfigData : TableSOBaseData<UFConfigType>
{
    //配置项索引
    public UFConfigType ConfigType;

    //资源名称
    public string AssetName;

    //Bundle名称
    public string BundleName;
}