// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Excel Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;
using BetaFramework;
public class UIBundleData : TableSOBaseData<string>
{
    //资源索引
    public string AssetKey;

    //Bundle名称
    public string BundleName;

    //资源名称
    public string AssetName;

}
