package com.imop.lj.gameserver.common.msg;

import java.util.HashMap;
import java.util.Map;

import com.imop.lj.core.msg.MessageType;
import com.imop.lj.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class CommonMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_SET_CONSUME_CONFIRM, CGSetConsumeConfirm.class);
		map.put(MessageType.CG_SELECT_OPTION, CGSelectOption.class);
		map.put(MessageType.CG_PING, CGPing.class);
		map.put(MessageType.CG_CLICK_NOTICE_TIPS_INFO, CGClickNoticeTipsInfo.class);
		map.put(MessageType.CG_SEND_NOTICE_TIPS, CGSendNoticeTips.class);
		map.put(MessageType.CG_OFFLINE_USER_BASE_INFO, CGOfflineUserBaseInfo.class);
		map.put(MessageType.CG_OFFLINE_USER_LEADER_INFO, CGOfflineUserLeaderInfo.class);
		map.put(MessageType.CG_OFFLINE_USER_PET_INFO, CGOfflineUserPetInfo.class);
		return map;
	}

}
