package com.imop.lj.gameserver.arena.msg;

import java.util.HashMap;
import java.util.Map;

import com.imop.lj.core.msg.MessageType;
import com.imop.lj.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class ArenaMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_SHOW_ARENA_PANEL, CGShowArenaPanel.class);
		map.put(MessageType.CG_ARENA_BUY_CHALLENGE_TIME, CGArenaBuyChallengeTime.class);
		map.put(MessageType.CG_ARENA_TOP_RANK_LIST, CGArenaTopRankList.class);
		map.put(MessageType.CG_ARENA_ATTACK_OPPONENT, CGArenaAttackOpponent.class);
		map.put(MessageType.CG_ARENA_REFRESH_OPPONENT, CGArenaRefreshOpponent.class);
		map.put(MessageType.CG_ARENA_KILL_CD, CGArenaKillCd.class);
		map.put(MessageType.CG_ARENA_BATTLE_RECORD, CGArenaBattleRecord.class);
		map.put(MessageType.CG_ARENA_RANK_REWARD_LIST, CGArenaRankRewardList.class);
		return map;
	}

}
