---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/1/25 11:57
---

_G.PublicUtil = {}

_G.printC     = function(str, color)
	if not color then
		color = "#00FF00"
	end
	print(string.format("<color='%s'>%s</color>", color, str))
end

---@note  返回道具数量显示文本(带颜色)
---@curNum 道具id
---@curNum 当前拥有数量
function PublicUtil:GetItemCount(itemId, curNum)
	local str = ""
	local num = BagModel:GetPlayerValue(itemId)
	if num >= curNum then
		if BagUtil:IsMoney(itemId) then
			str = string.format("<color=#FFFFFF>%s</color>", curNum)
		else
			str = string.format("<color=#FFFFFF>%s</color><color=#FFFFFF>/%s</color>", num, curNum)
		end
	else
		if BagUtil:IsMoney(itemId) then
			str = string.format("<color=#e32020>%s</color>", curNum)
		else
			str = string.format("<color=#e32020>%s</color><color=#ffffff>/%s</color>", num, curNum)
		end
	end
	return str
end

---@note  返回道具数量显示文本(带颜色)
---@curNum 道具id
---@curNum 当前拥有数量
function PublicUtil:GetItemCountNeedShowAll(itemId, curNum)
	local str = ""
	local num = BagModel:GetPlayerValue(itemId)
	if num >= curNum then
		str = string.format("<color=#FFFFFF>%s</color><color=#FFFFFF>/%s</color>", getNumShow2(num,1), getNumShow2(curNum,1))
	else
		str = string.format("<color=#e32020>%s</color><color=#ffffff>/%s</color>", getNumShow2(num,1), getNumShow2(curNum,1))
	end
	return str
end

---WriteLogToFile 写日志到文件
---@param data table
---@param fileName string
function PublicUtil:WriteLogToFile(data, fileName)
	do
		return
	end
	if not IsRunInEditor then return end
	if not fileName then
		fileName = tostring(CTimeFormat:sec8format(GetServerTime()))
	end
	fileName   = "Logs/" .. fileName .. ".Lua"
	local file = io.open(fileName, "a+")
	io.output(file)
	io.write('\n')
	local time = CTimeFormat:GetSecAsFormat(GetServerTime())
	time       = "local LogTime = " .. " '" .. time .. "'\n"
	io.write(time)
	if type(data) == 'table' then
		io.write("_G.LogData =" .. '\n')
	else
		io.write("LogStr = ")
	end
	io.write(LuaTableToString(data))
	io.close(file)
end
