// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2020-02-14 17:37:00.521
// ------------------------------------------------------------------------------

using System.Collections.Generic;

/// <summary>
/// 广告配置表
/// </summary>
public class AdsConfig : BaseSheet<AdsConfig_Data>
{
}