// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2020-02-14 17:37:00.517
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// 广告配置表数据
/// </summary>
public class AdsConfig_Data : BaseExcelData
{
    
    /// <summary>
    /// 激励视频公共CD
    /// </summary>
    public int RV_CD;

    /// <summary>
    /// 激励视频奖励金币数
    /// </summary>
    public int RV_RewardCoin;

    /// <summary>
    /// 激励视频每日最大次数
    /// </summary>
    public int RV_MaxCount;

    /// <summary>
    /// 局内激励视频出现等级
    /// </summary>
    public int GP_RV_BeginLevel;

    /// <summary>
    /// 局内激励视频是否显示
    /// </summary>
    public bool GP_RV_IsShown;

    /// <summary>
    /// 关商店激励视频出现等级
    /// </summary>
    public int CS_RV_BeginLevel;

    /// <summary>
    /// 关商店激励视频是否显示
    /// </summary>
    public bool CS_RV_IsShown;

    /// <summary>
    /// 商城激励视频出现等级
    /// </summary>
    public int SP_RV_BeginLevel;

    /// <summary>
    /// 商城激励视频是否显示
    /// </summary>
    public bool SP_RV_IsShown;

    /// <summary>
    /// LEVEL宝箱激励是否打开
    /// </summary>
    public bool tcRvSwitch;

    /// <summary>
    /// FLASH刷新激励是否打开
    /// </summary>
    public bool flashRvSwitch;

    /// <summary>
    /// 7天签到激励是否打开
    /// </summary>
    public bool signRvSwitch;

    /// <summary>
    /// 微博宝箱激励是否打开
    /// </summary>
    public bool blogRvSwitch;

    /// <summary>
    /// 插屏开关
    /// </summary>
    public bool inSwitch;

    /// <summary>
    /// 插屏出现等级
    /// </summary>
    public int IN_BeginLevel;

    /// <summary>
    /// 插屏CD（时间CD，本次不用）
    /// </summary>
    public int inCD;

    /// <summary>
    /// 插屏每日最大次数（去掉）
    /// </summary>
    public int inMaxCount;

    /// <summary>
    /// 插屏出现前打开多少次商店提前激活插屏（去掉）
    /// </summary>
    public int inShopOpenTimes;

    /// <summary>
    /// 插屏初期关卡初始值
    /// </summary>
    public int inEarlyBL;

    /// <summary>
    /// 插屏初期关卡结束值
    /// </summary>
    public int inEarlyEL;

    /// <summary>
    /// 插屏初期关卡CD
    /// </summary>
    public int inEarlyCD;

    /// <summary>
    /// 插屏中期关卡初始值
    /// </summary>
    public int inMidBL;

    /// <summary>
    /// 插屏中期关卡结束值
    /// </summary>
    public int inMidEL;

    /// <summary>
    /// 插屏中期关卡CD
    /// </summary>
    public int inMidCD;

    /// <summary>
    /// 插屏后期关卡初始值
    /// </summary>
    public int inLateBL;

    /// <summary>
    /// 插屏后期关卡结束值
    /// </summary>
    public int inLateEL;

    /// <summary>
    /// 插屏后期关卡CD
    /// </summary>
    public int inLateCD;

    /// <summary>
    /// 插屏是否每天第一关不弹1是0否
    /// </summary>
    public bool inDFirstSwitch;

    /// <summary>
    /// 每日挑战插屏开关
    /// </summary>
    public bool inDailySwitch;

    /// <summary>
    /// 每日挑战关卡CD
    /// </summary>
    public int inDailyCD;

    /// <summary>
    /// FLASH插屏开关
    /// </summary>
    public bool inFlashSwitch;

    /// <summary>
    /// Flash关卡CD
    /// </summary>
    public int inFlashCD;

    public int GetRowsCount()
    {
        return 4;
    }
    public int GetColumnsCount()
    {
        return 33;
    }
    public void Init(Dictionary<string, object> data)
    {
        
        ID = Convert.ToString(data["ID"]);
        RV_CD = Convert.ToInt32(data["RV_CD"]);
        RV_RewardCoin = Convert.ToInt32(data["RV_RewardCoin"]);
        RV_MaxCount = Convert.ToInt32(data["RV_MaxCount"]);
        GP_RV_BeginLevel = Convert.ToInt32(data["GP_RV_BeginLevel"]);
        GP_RV_IsShown = Convert.ToBoolean(data["GP_RV_IsShown"]);
        CS_RV_BeginLevel = Convert.ToInt32(data["CS_RV_BeginLevel"]);
        CS_RV_IsShown = Convert.ToBoolean(data["CS_RV_IsShown"]);
        SP_RV_BeginLevel = Convert.ToInt32(data["SP_RV_BeginLevel"]);
        SP_RV_IsShown = Convert.ToBoolean(data["SP_RV_IsShown"]);
        tcRvSwitch = Convert.ToBoolean(data["tcRvSwitch"]);
        flashRvSwitch = Convert.ToBoolean(data["flashRvSwitch"]);
        signRvSwitch = Convert.ToBoolean(data["signRvSwitch"]);
        blogRvSwitch = Convert.ToBoolean(data["blogRvSwitch"]);
        inSwitch = Convert.ToBoolean(data["inSwitch"]);
        IN_BeginLevel = Convert.ToInt32(data["IN_BeginLevel"]);
        inCD = Convert.ToInt32(data["inCD"]);
        inMaxCount = Convert.ToInt32(data["inMaxCount"]);
        inShopOpenTimes = Convert.ToInt32(data["inShopOpenTimes"]);
        inEarlyBL = Convert.ToInt32(data["inEarlyBL"]);
        inEarlyEL = Convert.ToInt32(data["inEarlyEL"]);
        inEarlyCD = Convert.ToInt32(data["inEarlyCD"]);
        inMidBL = Convert.ToInt32(data["inMidBL"]);
        inMidEL = Convert.ToInt32(data["inMidEL"]);
        inMidCD = Convert.ToInt32(data["inMidCD"]);
        inLateBL = Convert.ToInt32(data["inLateBL"]);
        inLateEL = Convert.ToInt32(data["inLateEL"]);
        inLateCD = Convert.ToInt32(data["inLateCD"]);
        inDFirstSwitch = Convert.ToBoolean(data["inDFirstSwitch"]);
        inDailySwitch = Convert.ToBoolean(data["inDailySwitch"]);
        inDailyCD = Convert.ToInt32(data["inDailyCD"]);
        inFlashSwitch = Convert.ToBoolean(data["inFlashSwitch"]);
        inFlashCD = Convert.ToInt32(data["inFlashCD"]);
    }
    override public string ToString()
    {
        return string.Format("ID={0},RV_CD={1},RV_RewardCoin={2},RV_MaxCount={3},GP_RV_BeginLevel={4},GP_RV_IsShown={5},CS_RV_BeginLevel={6},CS_RV_IsShown={7},SP_RV_BeginLevel={8},SP_RV_IsShown={9},tcRvSwitch={10},flashRvSwitch={11},signRvSwitch={12},blogRvSwitch={13},inSwitch={14},IN_BeginLevel={15},inCD={16},inMaxCount={17},inShopOpenTimes={18},inEarlyBL={19},inEarlyEL={20},inEarlyCD={21},inMidBL={22},inMidEL={23},inMidCD={24},inLateBL={25},inLateEL={26},inLateCD={27},inDFirstSwitch={28},inDailySwitch={29},inDailyCD={30},inFlashSwitch={31},inFlashCD={32}", ID, RV_CD, RV_RewardCoin, RV_MaxCount, GP_RV_BeginLevel, GP_RV_IsShown, CS_RV_BeginLevel, CS_RV_IsShown, SP_RV_BeginLevel, SP_RV_IsShown, tcRvSwitch, flashRvSwitch, signRvSwitch, blogRvSwitch, inSwitch, IN_BeginLevel, inCD, inMaxCount, inShopOpenTimes, inEarlyBL, inEarlyEL, inEarlyCD, inMidBL, inMidEL, inMidCD, inLateBL, inLateEL, inLateCD, inDFirstSwitch, inDailySwitch, inDailyCD, inFlashSwitch, inFlashCD);
    }
}