// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2020-02-15 10:59:19.073
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// 表数据
/// </summary>
public class BagItems_Data : BaseExcelData
{
    
    /// <summary>
    /// 描述
    /// </summary>
    public string ItemID;

    /// <summary>
    /// 图标
    /// </summary>
    public string Sprite;

    /// <summary>
    /// 名字
    /// </summary>
    public string Name;

    /// <summary>
    /// 灰色图标
    /// </summary>
    public string Gsprite;

    public int GetRowsCount()
    {
        return 10;
    }
    public int GetColumnsCount()
    {
        return 5;
    }
    public void Init(Dictionary<string, object> data)
    {
        
        ID = Convert.ToString(data["ID"]);
        ItemID = Convert.ToString(data["ItemID"]);
        Sprite = Convert.ToString(data["Sprite"]);
        Name = Convert.ToString(data["Name"]);
        Gsprite = Convert.ToString(data["Gsprite"]);
    }
    override public string ToString()
    {
        return string.Format("ID={0},ItemID={1},Sprite={2},Name={3},Gsprite={4}", ID, ItemID, Sprite, Name, Gsprite);
    }
}