// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2019-11-14 10:28:23.543
// ------------------------------------------------------------------------------

using System.Collections.Generic;

/// <summary>
/// 表
/// </summary>
public class BagItems : BaseSheet<BagItems_Data>
{
    public BagItems_Data GetTarget(string id)
    {
        for (int i = 0; i < dataList.Count; i++)
        {
            if (dataList[i].ID == id)
            {
                return dataList[i];
            }
        }

        return null;
    }
}