// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2019-09-26 15:07:44.493
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// 表数据
/// </summary>
public class EventLocalData_Data : BaseExcelData
{
    
    /// <summary>
    /// 该配置的版号
    /// </summary>
    public int ConfigVersion;

    /// <summary>
    /// 活动类别,
    /// </summary>
    public int ActivityGroup;

    /// <summary>
    /// 当前活动ID
    /// </summary>
    public int ActivityId;

    /// <summary>
    /// 即将开始,1:正在进行，-1：已经结束
    /// </summary>
    public int TimeType;

    /// <summary>
    /// 倒计时，结合前一个参数使用
    /// </summary>
    public int Countdown;

    /// <summary>
    /// 1:每日活动,2：限时活动
    /// </summary>
    public int ActivityType;

    /// <summary>
    /// 优先级
    /// </summary>
    public int Priority;

    /// <summary>
    /// 名字
    /// </summary>
    public string PrefabName;

    /// <summary>
    /// 名字
    /// </summary>
    public string PrefabSmallName;

    /// <summary>
    /// 主页是否显示 0 :不显示
    /// </summary>
    public int ShowHome;

    /// <summary>
    /// 结算显示界面
    /// </summary>
    public int Settlement;

    /// <summary>
    /// 特殊活动,额外配置
    /// </summary>
    public string Config;

    public int GetRowsCount()
    {
        return 4;
    }
    public int GetColumnsCount()
    {
        return 13;
    }
    public void Init(Dictionary<string, object> data)
    {
        
        ID = Convert.ToString(data["ID"]);
        ConfigVersion = Convert.ToInt32(data["ConfigVersion"]);
        ActivityGroup = Convert.ToInt32(data["ActivityGroup"]);
        ActivityId = Convert.ToInt32(data["ActivityId"]);
        TimeType = Convert.ToInt32(data["TimeType"]);
        Countdown = Convert.ToInt32(data["Countdown"]);
        ActivityType = Convert.ToInt32(data["ActivityType"]);
        Priority = Convert.ToInt32(data["Priority"]);
        PrefabName = Convert.ToString(data["PrefabName"]);
        PrefabSmallName = Convert.ToString(data["PrefabSmallName"]);
        ShowHome = Convert.ToInt32(data["ShowHome"]);
        Settlement = Convert.ToInt32(data["Settlement"]);
        Config = Convert.ToString(data["Config"]);
    }
    override public string ToString()
    {
        return string.Format("ID={0},ConfigVersion={1},ActivityGroup={2},ActivityId={3},TimeType={4},Countdown={5},ActivityType={6},Priority={7},PrefabName={8},PrefabSmallName={9},ShowHome={10},Settlement={11},Config={12}", ID, ConfigVersion, ActivityGroup, ActivityId, TimeType, Countdown, ActivityType, Priority, PrefabName, PrefabSmallName, ShowHome, Settlement, Config);
    }
}