// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2019-08-28 18:38:24.911
// ------------------------------------------------------------------------------

using System.Collections.Generic;

/// <summary>
/// Hint提示配置表
/// </summary>
public class HintConfig : BaseSheet<HintConfig_Data>
{
}