// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2020-02-13 10:55:20.637
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// 商店配置-craze新需求(2)表数据
/// </summary>
public class IapProductConfig_Data : BaseExcelData
{
    public ReportUserBuyData _customData;

    /// <summary>
    /// 内购idp
    /// </summary>
    public string ProductID;

    public int ItemID;
    /// <summary>
    /// 0 正常 1 去广告
    /// </summary>
    public int ProductType;

    /// <summary>
    /// 内购美元价格
    /// </summary>
    public string ProductDollarPrice;

    /// <summary>
    /// 获得金币数
    /// </summary>
    public int ProductCoins;

    /// <summary>
    /// 获得hint1数
    /// </summary>
    public int ProductHint1;

    /// <summary>
    /// 获得hint2数
    /// </summary>
    public int ProductHint2;

    /// <summary>
    /// 获得hint3数
    /// </summary>
    public int ProductHint3;

    /// <summary>
    /// 获得hint4数
    /// </summary>
    public int ProductHint4;

    /// <summary>
    /// 获得hint5数
    /// </summary>
    public int ProductHint5;

    /// <summary>
    /// 0-常规内购项 1-新手礼包 2-促销礼包 3-常驻礼包
    /// </summary>
    public int IapType;

    /// <summary>
    /// （-1）不需要image配置，0-1-2-3-4
    /// </summary>
    public int ImageType;

    /// <summary>
    /// X% more
    /// </summary>
    public string PercentMore;

    /// <summary>
    /// 礼包title
    /// </summary>
    public string TitleName;

    /// <summary>
    /// LocalizedTitle
    /// </summary>
    public string LocalizedTitle;

    /// <summary>
    /// 货币类型
    /// </summary>
    public string IsoCurrencyCode;

    /// <summary>
    /// 订单id
    /// </summary>
    public string TransactionID;

    /// <summary>
    /// 订单详细信息
    /// </summary>
    public string Receipt;

    /// <summary>
    /// 是否内购过此类型内购项
    /// </summary>
    public bool IsPurchaserSucceed;

    /// <summary>
    /// 本地价格
    /// </summary>
    public string ProductLocalizedPrice;

    /// <summary>
    /// 本地价格    不带货币符号
    /// </summary>
    public Decimal ProductLocalizedPriceValue;

    /// <summary>
    /// 1-normal 普通内购项 2-resident 常驻礼包3-removeads单独去广告4-shopgreenhand商城内新手礼包5-shoplimitsale商城内促销礼包6-dialoggreenhand弹版新手礼包7-dialoglimitsale弹版促销礼包8-restore
    /// </summary>
    public string PayType;

    /// <summary>
    /// 礼包id
    /// </summary>
    public int GiftId;

    /// <summary>
    /// 剩余时间
    /// </summary>
    public int RemainTime;

    /// <summary>
    /// 奖励弹窗的宝箱类型
    /// </summary>
    public int RewardBox;

    /// <summary>
    /// 是否去广告0 否1 是
    /// </summary>
    public int removeAd;

    /// <summary>
    /// 角标0 POPULAR 1 BEST 2 SALE
    /// </summary>
    public int Subscript;

    public int GetRowsCount()
    {
        return 14;
    }
    public int GetColumnsCount()
    {
        return 26;
    }
    public void Init(Dictionary<string, object> data)
    {
        
        ID = Convert.ToString(data["ID"]);
        ProductID = Convert.ToString(data["ProductID"]);
        ProductType = Convert.ToInt32(data["ProductType"]);
        ProductDollarPrice = Convert.ToString(data["ProductDollarPrice"]);
        ProductCoins = Convert.ToInt32(data["ProductCoins"]);
        ProductHint1 = Convert.ToInt32(data["ProductHint1"]);
        ProductHint2 = Convert.ToInt32(data["ProductHint2"]);
        ProductHint3 = Convert.ToInt32(data["ProductHint3"]);
        ProductHint4 = Convert.ToInt32(data["ProductHint4"]);
        ProductHint5 = Convert.ToInt32(data["ProductHint5"]);
        IapType = Convert.ToInt32(data["IapType"]);
        ImageType = Convert.ToInt32(data["ImageType"]);
        PercentMore = Convert.ToString(data["PercentMore"]);
        TitleName = Convert.ToString(data["TitleName"]);
        LocalizedTitle = Convert.ToString(data["LocalizedTitle"]);
        IsoCurrencyCode = Convert.ToString(data["IsoCurrencyCode"]);
        TransactionID = Convert.ToString(data["TransactionID"]);
        Receipt = Convert.ToString(data["Receipt"]);
        IsPurchaserSucceed = Convert.ToBoolean(data["IsPurchaserSucceed"]);
        ProductLocalizedPrice = Convert.ToString(data["ProductLocalizedPrice"]);
        PayType = Convert.ToString(data["PayType"]);
        GiftId = Convert.ToInt32(data["GiftId"]);
        RemainTime = Convert.ToInt32(data["RemainTime"]);
        RewardBox = Convert.ToInt32(data["RewardBox"]);
        removeAd = Convert.ToInt32(data["removeAd"]);
        Subscript = Convert.ToInt32(data["Subscript"]);
    }
    override public string ToString()
    {
        return string.Format("ID={0},ProductID={1},ProductType={2},ProductDollarPrice={3},ProductCoins={4},ProductHint1={5},ProductHint2={6},ProductHint3={7},ProductHint4={8},ProductHint5={9},IapType={10},ImageType={11},PercentMore={12},TitleName={13},LocalizedTitle={14},IsoCurrencyCode={15},TransactionID={16},Receipt={17},IsPurchaserSucceed={18},ProductLocalizedPrice={19},PayType={20},GiftId={21},RemainTime={22},RewardBox={23},removeAd={24},Subscript={25}", ID, ProductID, ProductType, ProductDollarPrice, ProductCoins, ProductHint1, ProductHint2, ProductHint3, ProductHint4, ProductHint5, IapType, ImageType, PercentMore, TitleName, LocalizedTitle, IsoCurrencyCode, TransactionID, Receipt, IsPurchaserSucceed, ProductLocalizedPrice, PayType, GiftId, RemainTime, RewardBox, removeAd, Subscript);
    }
}