// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2019-09-26 15:07:44.658
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// 地图配置表数据
/// </summary>
public class MapConfig_Data : BaseExcelData
{
    
    /// <summary>
    /// 大世界索引
    /// </summary>
    public int WorldIndex;

    /// <summary>
    /// 小世界索引
    /// </summary>
    public int SubWorldIndex;

    /// <summary>
    /// 大世界名称
    /// </summary>
    public string WorldName;

    /// <summary>
    /// 黑白格（0是白，1黑）
    /// </summary>
    public int CellType;

    /// <summary>
    /// 词格填充，连线，词盘字母背景
    /// </summary>
    public string PanColor;

    /// <summary>
    /// 地图小世界Level盘颜色
    /// </summary>
    public string LevelColorIn;

    /// <summary>
    /// 地图小世界Level盘外轮廓颜色
    /// </summary>
    public string LevelColorOut;

    /// <summary>
    /// 每个世界多少关
    /// </summary>
    public int LevelCount;

    /// <summary>
    /// subword完成奖励ID
    /// </summary>
    public string SubwordReward;

    public int GetRowsCount()
    {
        return 143;
    }
    public int GetColumnsCount()
    {
        return 10;
    }
    public void Init(Dictionary<string, object> data)
    {
        
        ID = Convert.ToString(data["ID"]);
        WorldIndex = Convert.ToInt32(data["WorldIndex"]);
        SubWorldIndex = Convert.ToInt32(data["SubWorldIndex"]);
        WorldName = Convert.ToString(data["WorldName"]);
        CellType = Convert.ToInt32(data["CellType"]);
        PanColor = Convert.ToString(data["PanColor"]);
        LevelColorIn = Convert.ToString(data["LevelColorIn"]);
        LevelColorOut = Convert.ToString(data["LevelColorOut"]);
        LevelCount = Convert.ToInt32(data["LevelCount"]);
        SubwordReward = Convert.ToString(data["SubwordReward"]);
    }
    override public string ToString()
    {
        return string.Format("ID={0},WorldIndex={1},SubWorldIndex={2},WorldName={3},CellType={4},PanColor={5},LevelColorIn={6},LevelColorOut={7},LevelCount={8},SubwordReward={9}", ID, WorldIndex, SubWorldIndex, WorldName, CellType, PanColor, LevelColorIn, LevelColorOut, LevelCount, SubwordReward);
    }
}