// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2019-09-26 15:07:44.744
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// 默认昵称表数据
/// </summary>
public class NameConfig_Data : BaseExcelData
{
    
    /// <summary>
    /// 昵称
    /// </summary>
    public string Name;

    public int GetRowsCount()
    {
        return 460;
    }
    public int GetColumnsCount()
    {
        return 2;
    }
    public void Init(Dictionary<string, object> data)
    {
        
        ID = Convert.ToString(data["ID"]);
        Name = Convert.ToString(data["Name"]);
    }
    override public string ToString()
    {
        return string.Format("ID={0},Name={1}", ID, Name);
    }
}