// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2019-09-26 15:07:44.746
// ------------------------------------------------------------------------------

using System.Collections.Generic;

/// <summary>
/// 默认昵称表
/// </summary>
public class NameConfig : BaseSheet<NameConfig_Data>
{
    public string GetRandomName()
    {
        int index = UnityEngine.Random.Range(0, dataList.Count);
        return dataList[index].Name;
    }
}