// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2019-12-23 17:55:44.093
// ------------------------------------------------------------------------------

using System.Collections.Generic;

/// <summary>
/// 表
/// </summary>
public class PlayerSign : BaseSheet<PlayerSign_Data>
{
}