// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2019-10-09 15:05:35.847
// ------------------------------------------------------------------------------

using System.Collections.Generic;

/// <summary>
/// 表
/// </summary>
public class ProbabilityPool : BaseSheet<ProbabilityPool_Data>
{
}