// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2020-08-20 20:02:00.958
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// 表数据
/// </summary>
public class PropertyAB_Data : BaseExcelData
{
    
    /// <summary>
    /// 价格
    /// </summary>
    public int Coast;

    /// <summary>
    /// 开启关卡
    /// </summary>
    public int StartLevel;

    /// <summary>
    /// 默认数量
    /// </summary>
    public int DefaultCount;

    public int GetRowsCount()
    {
        return 9;
    }
    public int GetColumnsCount()
    {
        return 4;
    }
    public void Init(Dictionary<string, object> data)
    {
        
        ID = Convert.ToString(data["ID"]);
        Coast = Convert.ToInt32(data["Coast"]);
        StartLevel = Convert.ToInt32(data["StartLevel"]);
        DefaultCount = Convert.ToInt32(data["DefaultCount"]);
    }
    override public string ToString()
    {
        return string.Format("ID={0},Coast={1},StartLevel={2},DefaultCount={3}", ID, Coast, StartLevel, DefaultCount);
    }
}