// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2019-09-26 15:07:44.773
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// 评价配置表数据
/// </summary>
public class RateConfig_Data : BaseExcelData
{
    
    /// <summary>
    /// 评价系统是否开启
    /// </summary>
    public bool IsShown;

    /// <summary>
    ///  第一次弹出评价关卡
    /// </summary>
    public int FirstBeginLevel;

    /// <summary>
    /// 第二次弹出评价关卡
    /// </summary>
    public int SecondBeginLevel;

    /// <summary>
    /// 是否开启过滤评价
    /// </summary>
    public bool IsFilterComment;

    /// <summary>
    /// 评价赠给玩家金币数
    /// </summary>
    public int RewardCoin;

    public int GetRowsCount()
    {
        return 4;
    }
    public int GetColumnsCount()
    {
        return 6;
    }
    public void Init(Dictionary<string, object> data)
    {
        
        ID = Convert.ToString(data["ID"]);
        IsShown = Convert.ToBoolean(data["IsShown"]);
        FirstBeginLevel = Convert.ToInt32(data["FirstBeginLevel"]);
        SecondBeginLevel = Convert.ToInt32(data["SecondBeginLevel"]);
        IsFilterComment = Convert.ToBoolean(data["IsFilterComment"]);
        RewardCoin = Convert.ToInt32(data["RewardCoin"]);
    }
    override public string ToString()
    {
        return string.Format("ID={0},IsShown={1},FirstBeginLevel={2},SecondBeginLevel={3},IsFilterComment={4},RewardCoin={5}", ID, IsShown, FirstBeginLevel, SecondBeginLevel, IsFilterComment, RewardCoin);
    }
}