// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2020-06-28 16:34:00.326
// ------------------------------------------------------------------------------

using System.Collections.Generic;

/// <summary>
/// 表
/// </summary>
public class RewardAB : BaseSheet<RewardAB_Data>
{
    public string reportStr;
}