// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2019-09-26 15:07:44.872
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// 小人系列表表数据
/// </summary>
public class WordMasterTheme_Data : BaseExcelData
{
    
    /// <summary>
    /// 系列名称
    /// </summary>
    public string Name;

    /// <summary>
    /// 介绍
    /// </summary>
    public string Descrip;

    /// <summary>
    /// 系列顺序
    /// </summary>
    public int Order;

    /// <summary>
    /// 系列小ICON
    /// </summary>
    public string SmallIcon;

    /// <summary>
    /// 系列大ICON
    /// </summary>
    public string Logo;

    /// <summary>
    /// 系列主背景图
    /// </summary>
    public string ThemeBG;

    /// <summary>
    /// 子系列背景图
    /// </summary>
    public string SubThemeBG;

    /// <summary>
    /// 开放星级
    /// </summary>
    public int OpenStar;

    /// <summary>
    /// 主题集齐奖励1
    /// </summary>
    public string Reward1;

    /// <summary>
    /// 奖励1数量
    /// </summary>
    public int Reward1Count;

    /// <summary>
    /// 主题集齐奖励2
    /// </summary>
    public string Reward2;

    /// <summary>
    /// 奖励2数量
    /// </summary>
    public int Reward2Count;

    /// <summary>
    /// 主题集齐奖励3
    /// </summary>
    public string Reward3;

    /// <summary>
    /// 奖励3数量
    /// </summary>
    public int Reward3Count;

    /// <summary>
    /// 开始时间
    /// </summary>
    public string StartTime;

    /// <summary>
    /// 结束时间
    /// </summary>
    public string EndTime;

    /// <summary>
    /// 层数
    /// </summary>
    public int SubCounts;

    /// <summary>
    /// 主题分层1小人
    /// </summary>
    public string Sub1Master;

    /// <summary>
    /// 主题分层1奖励
    /// </summary>
    public string Sub1Reward;

    /// <summary>
    /// 主题分层1奖励数量
    /// </summary>
    public int Sub1RewardCount;

    /// <summary>
    /// 主题分层2小人
    /// </summary>
    public string Sub2Master;

    /// <summary>
    /// 主题分层2奖励
    /// </summary>
    public string Sub2Reward;

    /// <summary>
    /// 主题分层2奖励数量
    /// </summary>
    public int Sub2Count;

    /// <summary>
    /// 主题分层3小人
    /// </summary>
    public string Sub3Master;

    /// <summary>
    /// 主题分层3奖励
    /// </summary>
    public string Sub3Reward;

    /// <summary>
    /// 主题分层3奖励数量
    /// </summary>
    public int Sub3Count;

    /// <summary>
    /// 主题分层4小人
    /// </summary>
    public string Sub4Master;

    /// <summary>
    /// 主题分层4奖励
    /// </summary>
    public string Sub4Reward;

    /// <summary>
    /// 主题分层4奖励数量
    /// </summary>
    public int Sub4Count;

    /// <summary>
    /// 主题分层5小人
    /// </summary>
    public string Sub5Master;

    /// <summary>
    /// 主题分层5奖励
    /// </summary>
    public string Sub5Reward;

    /// <summary>
    /// 主题分层5奖励数量
    /// </summary>
    public int Sub5Count;

    /// <summary>
    /// 资源在本地
    /// </summary>
    public int LocalRes;

    public int GetRowsCount()
    {
        return 11;
    }
    public int GetColumnsCount()
    {
        return 34;
    }
    public void Init(Dictionary<string, object> data)
    {
        
        ID = Convert.ToString(data["ID"]);
        Name = Convert.ToString(data["Name"]);
        Descrip = Convert.ToString(data["Descrip"]);
        Order = Convert.ToInt32(data["Order"]);
        SmallIcon = Convert.ToString(data["SmallIcon"]);
        Logo = Convert.ToString(data["Logo"]);
        ThemeBG = Convert.ToString(data["ThemeBG"]);
        SubThemeBG = Convert.ToString(data["SubThemeBG"]);
        OpenStar = Convert.ToInt32(data["OpenStar"]);
        Reward1 = Convert.ToString(data["Reward1"]);
        Reward1Count = Convert.ToInt32(data["Reward1Count"]);
        Reward2 = Convert.ToString(data["Reward2"]);
        Reward2Count = Convert.ToInt32(data["Reward2Count"]);
        Reward3 = Convert.ToString(data["Reward3"]);
        Reward3Count = Convert.ToInt32(data["Reward3Count"]);
        StartTime = Convert.ToString(data["StartTime"]);
        EndTime = Convert.ToString(data["EndTime"]);
        SubCounts = Convert.ToInt32(data["SubCounts"]);
        Sub1Master = Convert.ToString(data["Sub1Master"]);
        Sub1Reward = Convert.ToString(data["Sub1Reward"]);
        Sub1RewardCount = Convert.ToInt32(data["Sub1RewardCount"]);
        Sub2Master = Convert.ToString(data["Sub2Master"]);
        Sub2Reward = Convert.ToString(data["Sub2Reward"]);
        Sub2Count = Convert.ToInt32(data["Sub2Count"]);
        Sub3Master = Convert.ToString(data["Sub3Master"]);
        Sub3Reward = Convert.ToString(data["Sub3Reward"]);
        Sub3Count = Convert.ToInt32(data["Sub3Count"]);
        Sub4Master = Convert.ToString(data["Sub4Master"]);
        Sub4Reward = Convert.ToString(data["Sub4Reward"]);
        Sub4Count = Convert.ToInt32(data["Sub4Count"]);
        Sub5Master = Convert.ToString(data["Sub5Master"]);
        Sub5Reward = Convert.ToString(data["Sub5Reward"]);
        Sub5Count = Convert.ToInt32(data["Sub5Count"]);
        LocalRes = Convert.ToInt32(data["LocalRes"]);
    }
    override public string ToString()
    {
        return string.Format("ID={0},Name={1},Descrip={2},Order={3},SmallIcon={4},Logo={5},ThemeBG={6},SubThemeBG={7},OpenStar={8},Reward1={9},Reward1Count={10},Reward2={11},Reward2Count={12},Reward3={13},Reward3Count={14},StartTime={15},EndTime={16},SubCounts={17},Sub1Master={18},Sub1Reward={19},Sub1RewardCount={20},Sub2Master={21},Sub2Reward={22},Sub2Count={23},Sub3Master={24},Sub3Reward={25},Sub3Count={26},Sub4Master={27},Sub4Reward={28},Sub4Count={29},Sub5Master={30},Sub5Reward={31},Sub5Count={32},LocalRes={33}", ID, Name, Descrip, Order, SmallIcon, Logo, ThemeBG, SubThemeBG, OpenStar, Reward1, Reward1Count, Reward2, Reward2Count, Reward3, Reward3Count, StartTime, EndTime, SubCounts, Sub1Master, Sub1Reward, Sub1RewardCount, Sub2Master, Sub2Reward, Sub2Count, Sub3Master, Sub3Reward, Sub3Count, Sub4Master, Sub4Reward, Sub4Count, Sub5Master, Sub5Reward, Sub5Count, LocalRes);
    }
}