// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2019-09-26 15:07:44.875
// ------------------------------------------------------------------------------

using System.Collections.Generic;

/// <summary>
/// 小人系列表表
/// </summary>
public class WordMasterTheme : BaseSheet<WordMasterTheme_Data>
{
}