// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the FrameWork Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
//  Build Time：2019-09-26 15:07:44.897
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// 小人表表数据
/// </summary>
public class WordMaster_Data : BaseExcelData
{
    
    /// <summary>
    /// 系列ID
    /// </summary>
    public int Theme_Id;

    /// <summary>
    /// 名字
    /// </summary>
    public string Name;

    /// <summary>
    /// 星级
    /// </summary>
    public int Star;

    /// <summary>
    /// 介绍
    /// </summary>
    public string Descrip;

    /// <summary>
    /// 缩略图资源
    /// </summary>
    public string Thumb;

    /// <summary>
    /// UI资源
    /// </summary>
    public string Resource;

    /// <summary>
    /// 小人Prefab
    /// </summary>
    public string Ani1;

    /// <summary>
    /// 动画资源2
    /// </summary>
    public string Ani2;

    /// <summary>
    /// 排序
    /// </summary>
    public int Order;

    /// <summary>
    /// 资源在本地
    /// </summary>
    public int LocalRes;

    public int GetRowsCount()
    {
        return 43;
    }
    public int GetColumnsCount()
    {
        return 11;
    }
    public void Init(Dictionary<string, object> data)
    {
        
        ID = Convert.ToString(data["ID"]);
        Theme_Id = Convert.ToInt32(data["Theme_Id"]);
        Name = Convert.ToString(data["Name"]);
        Star = Convert.ToInt32(data["Star"]);
        Descrip = Convert.ToString(data["Descrip"]);
        Thumb = Convert.ToString(data["Thumb"]);
        Resource = Convert.ToString(data["Resource"]);
        Ani1 = Convert.ToString(data["Ani1"]);
        Ani2 = Convert.ToString(data["Ani2"]);
        Order = Convert.ToInt32(data["Order"]);
        LocalRes = Convert.ToInt32(data["LocalRes"]);
    }
    override public string ToString()
    {
        return string.Format("ID={0},Theme_Id={1},Name={2},Star={3},Descrip={4},Thumb={5},Resource={6},Ani1={7},Ani2={8},Order={9},LocalRes={10}", ID, Theme_Id, Name, Star, Descrip, Thumb, Resource, Ani1, Ani2, Order, LocalRes);
    }
}