// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEditor;
public class BuildAndroid:Editor
{
	[MenuItem("File/Build Android Project")]
	static public void genAndroidProj(){
		BuildPipeline.BuildPlayer(new string[] { "Assets/Scene/GameClient.unity" }, Application.dataPath + "/../../android_unity_auto", 
		BuildTarget.Android, BuildOptions.AcceptExternalModificationsToPlayer);
        Debug.Log("call genAndroidProj end");
	}

}

