package com.imop.lj.gameserver.battle.msg;

import java.util.HashMap;
import java.util.Map;

import com.imop.lj.core.msg.MessageType;
import com.imop.lj.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class BattleMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_PLAY_BATTLE_REPORT, CGPlayBattleReport.class);
		map.put(MessageType.CG_PLAY_BATTLE_REPORT_BY_STR_ID, CGPlayBattleReportByStrId.class);
		map.put(MessageType.CG_BATTLE_NEXT_ROUND, CGBattleNextRound.class);
		map.put(MessageType.CG_BATTLE_START_PVP, CGBattleStartPvp.class);
		map.put(MessageType.CG_BATTLE_PVP_CANCEL_AUTO, CGBattlePvpCancelAuto.class);
		map.put(MessageType.CG_BATTLE_NEXT_ROUND_PVP, CGBattleNextRoundPvp.class);
		map.put(MessageType.CG_BATTLE_UPDATE_AUTO_ACTION, CGBattleUpdateAutoAction.class);
		map.put(MessageType.CG_BATTLE_TEAM_CANCEL_AUTO, CGBattleTeamCancelAuto.class);
		map.put(MessageType.CG_BATTLE_NEXT_ROUND_TEAM, CGBattleNextRoundTeam.class);
		map.put(MessageType.CG_BATTLE_LEADER_READY_PVP, CGBattleLeaderReadyPvp.class);
		map.put(MessageType.CG_BATTLE_LEADER_READY_TEAM, CGBattleLeaderReadyTeam.class);
		map.put(MessageType.CG_BATTLE_READ_REPORT_END, CGBattleReadReportEnd.class);
		map.put(MessageType.CG_BATTLE_START_TEAMPVP, CGBattleStartTeampvp.class);
		map.put(MessageType.CG_BATTLE_START_PVP_CONFIRM, CGBattleStartPvpConfirm.class);
		map.put(MessageType.CG_BATTLE_SPEEDUP, CGBattleSpeedup.class);
		return map;
	}

}
