namespace Hotfix {public class ViewConst{
//Group：PackTogether ;Label:prefab;
     public const string prefab_MapController = "MapController.prefab";
//Group：PackTogether ;Label:prefab;
     public const string prefab_UIJFly = "UIJFly.prefab";
//Group：PackTogether ;Label:prefab;
     public const string prefab_UIJLogin = "UIJLogin.prefab";
//Group：PackTogether ;Label:prefab;
     public const string prefab_UIManager = "UIManager.prefab";
//Group：PackTogether ;Label:prefab;
     public const string dll_Hotfix = "Hotfix.dll.bytes";
//Group：PackTogether ;Label:prefab;
     public const string pdb_Hotfix = "Hotfix.pdb.bytes";
//Group：PackTogether ;Label:prefab;
     public const string prefab_GameMap = "GameMap.prefab";
//Group：PackTogether ;Label:prefab;
     public const string prefab_NPC = "NPC.prefab";
//Group：PackTogether ;Label:Config;
     public const string txt_BuffConfig = "BuffConfig.txt";
//Group：PackTogether ;Label:Config;
     public const string txt_defendMonster = "defendMonster.txt";
//Group：PackTogether ;Label:Config;
     public const string txt_directfly = "directfly.txt";
//Group：PackTogether ;Label:Config;
     public const string txt_GlobalProto = "GlobalProto.txt";
//Group：PackTogether ;Label:Config;
     public const string txt_itemdef = "itemdef.txt";
//Group：PackTogether ;Label:Config;
     public const string txt_itemStack = "itemStack.txt";
//Group：PackTogether ;Label:Config;
     public const string txt_Levelinfo = "Levelinfo.txt";
//Group：PackTogether ;Label:Config;
     public const string txt_mapinfo = "mapinfo.txt";
//Group：PackTogether ;Label:Config;
     public const string txt_mondef = "mondef.txt";
//Group：PackTogether ;Label:Config;
     public const string txt_mondrop = "mondrop.txt";
//Group：PackTogether ;Label:Config;
     public const string txt_npcgen = "npcgen.txt";
//Group：PackTogether ;Label:Config;
     public const string txt_UnitConfig = "UnitConfig.txt";
}}