package com.imop.lj.gameserver.relation.msg;

import java.util.HashMap;
import java.util.Map;

import com.imop.lj.core.msg.MessageType;
import com.imop.lj.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class RelationMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_CLICK_RELATION_PANEL, CGClickRelationPanel.class);
		map.put(MessageType.CG_ADD_RELATION_BY_NAME, CGAddRelationByName.class);
		map.put(MessageType.CG_ADD_RELATION_BY_ID, CGAddRelationById.class);
		map.put(MessageType.CG_ADD_RELATION_BY_ID_STR, CGAddRelationByIdStr.class);
		map.put(MessageType.CG_ADD_RELATION_BATCH, CGAddRelationBatch.class);
		map.put(MessageType.CG_DEL_RELATION, CGDelRelation.class);
		map.put(MessageType.CG_SHOW_RECOMMEND_FRIEND_LIST, CGShowRecommendFriendList.class);
		return map;
	}

}
