public class FunctionIdDef
{
    public const int RENWU = 1;//任务
    public const int DUIWU = 2;//队伍
    public const int GUAJI = 3;//挂机
    public const int HUODONG = 4;//活动
    public const int JINGJICHANG = 5;//竞技场
    public const int JIUGUAN = 6;//酒馆
    public const int KEJU = 7;//朝云科举
    public const int XITONG = 8;//系统
    public const int PETSTORE = 9;//宠物商店
    public const int SHANGHUI = 10;//商会
    public const int PAIMAIHANG = 11;//拍卖行
    public const int CHONGZHI = 12;//充值
    public const int WUXING = 13;//悟性
    public const int BEIBAO = 14;//背包
    public const int XINFAJINENG = 15;//心法技能
    public const int BANGPAI = 16;//帮派成员申请
    public const int HUOBAN = 17;//伙伴
    public const int ZHENXING = 18;//阵型
    public const int PAIHANG = 19;//排行
    public const int DAZAO = 20;//打造
    public const int SHENGXING = 21;//升星
    public const int XIANGQIAN = 22;//宝石镶嵌
    public const int HECHENG = 23;//宝石合成
    public const int QIANGHUA = 24;//强化
    public const int FENJIE = 25;//分解
    public const int CHONGZHU = 26;//重铸
    public const int XILIAN = 27;//洗炼
    public const int GUANZHU = 28;//灌注
    public const int CHUANCHENG = 29;//传承
    public const int QIANDAO = 31;//每日签到
    public const int DENGLUJIANGLI = 32;//登陆奖励
    public const int ZAIXIANJIANGLI = 33;//在线奖励
    public const int YOUJIAN = 34;//邮件
    public const int HAOYOU = 35;//好友
    public const int CHENGJIU = 36;//成就
    public const int TISHENG = 37;//提升
    public const int GMBUCHANG = 38;//GM补偿
    public const int SHENMISHOP = 39;//神秘商店
    public const int JINGCAIHUODONG = 40;//精彩活动
    public const int VIP = 41;//VIP
    public const int JINJUANTAOCAN = 42;//金卷套餐
    public const int ZAIXIANLIBAO = 43;//特殊在线礼包
    public const int QICHONG = 44;//骑宠
    public const int CAIKUANG = 45;//采矿
    public const int CHUBAOANLIANG = 46;//除暴安良
    public const int LVYEXIANZONG = 47;//绿野仙踪
    public const int BAOTU = 48;//宝图任务
    public const int BPJS = 50;//帮派竞赛
    public const int YUNLIANG = 51;//护送粮草
    public const int SHITU = 52;//师徒
    public const int HUNYIN = 53;//结婚
    public const int NVSN = 54;//NVN联赛
    public const int CHONGWUDAO = 55;//宠物岛
    public const int CHIBANG = 56;//翅膀
    public const int CORPSTASK = 57;//帮派任务
    public const int CORPBUILD = 58;//帮派建设
    public const int CORPBENIFIT = 59;//帮派福利
    public const int DUIHUANJIANGLI = 60;//兑换奖励
    public const int TOWER = 61;//通天塔
    public const int CORPS_ACTIVITY = 62;//帮派活动
    public const int CORPS_BOSS = 63;//帮派boss.
    public const int FENGYAO_XIAOYAO = 64;//封妖 小妖
    public const int FENGYAO_MOWANG = 65;//封妖 魔王
    public const int HUNSHIMOWANG = 66;//封妖 混世魔王
    public const int XIANSHI_DATI = 67;//限时答题
    public const int XIANSHI_SHAGUAI = 68;//限时杀怪
    public const int XIANSHI_NPC = 69;//限时NPC
    public const int BANGPAIXIULIAN = 70;//帮派修炼
    public const int BANGPAIFUZHU = 71;//帮派辅助
    public const int BANGPAIHONGBAO = 72;//帮派红包
    public const int QIRIMUBIAO = 73;//七日目标

    public const int DANRENFUBEN = 75;//单人副本
    public const int JINGCAIHUODONG2 = 76;//精彩活动2（充值活动）
    public const int PUTONGMOZU = 77;//魔族副本-普通
    public const int KUNNANMOZU = 78;//魔族副本-困难
    public const int XIANHU = 79;//仙葫
    public const int NEWGUAJI = 80;//野外挂机
    public const int SHENGHUOJINENG = 81;//生活技能
    public const int SHENGHUOJINENG_STORE = 82;//生活技能书商店
    public const int YUEKA = 83;//月卡
    public const int RINGTASK = 84;//环任务
    /*-----以下功能客户端独有-----*/
    public const int JIANGLI = 10001;//奖励
    public const int PETSINFO = 10002;//宠物信息(点击主界面右上角的宠物头像后弹出)
    public const int ROLEINFO = 10003;//人物信息(点击主界面右上角的人物头像后弹出)
    public const int WORLDMAP = 10004;//世界地图
    public const int LVYEXIANZONG_DANREN = 10005;//绿野仙踪单人
    public const int LVYEXIANZONG_ZUDUI = 10006;//绿野仙踪多人
    public const int CHENGHAO = 10007;//称号
    public const int BPJS_Enter = 10008;//帮派竞赛进入
    public const int BPJS_Paihang = 10009;//帮派竞赛排行
    public const int SHITU_SHOUTU = 10010;//师徒-收徒
    public const int SHITU_CHUSHI = 10011;//师徒-出师
    public const int SHITU_JIECHU = 10012;//师徒-解除师徒关系
    public const int JIEHUN_WE = 10013;//我要结婚
    public const int LIHUN_WE = 10014;//我要离婚
    public const int CHONGWUDAO_YI = 10015;//宠物岛一层
    public const int CHONGWUDAO_ER = 10016;//宠物岛二层
    public const int CHONGWUDAO_SAN = 10017;//宠物岛三层
    public const int CHONGWUDAO_SI = 10018;//宠物岛四层
    public const int JUESEJIADIAN = 10019;//角色加点
    public const int CHONGWU = 10020;//宠物
    public const int CHONGWU_JIADIAN = 10021;//宠物升级
    public const int JINENGSHENGJI = 10022;//技能升级

    public const int TOWER_BEAST = 1023;//查看通天塔最优通关
    public const int TOWER_EARLIEST = 1024;//查看通天塔最早击杀
    public const int CORPSBOSS_CHANLLGE = 1025;//挑战帮派Boss
    public const int CORPSBOSS_BEAST = 1026;//查看帮派最优
    public const int CANGKU = 1027;//仓库

    public const int JINGJICHANGSHOP = 1028;//竞技场商店
    public const int PETTALENTSKILL = 1029;//宠物天赋技能
    public const int ROLESKILL = 1030;//角色技能
    public const int ROLE_ADDPOINT = 1031;//角色加点
    public const int STORY_VIDEO = 1032;//过场动画

    public const int XIAN_HU_ZUORI = 1033;//祈福仙葫昨日
    public const int LING_XI_XIANHU_ZUORI = 1034;//灵犀仙葫昨日
    public const int LING_XI_XIANHU_SHANGZHOU = 1035;//灵犀仙葫上周
    public const int XINFASHENGJI = 10036;//心法升级
    public const int QICHONGJIADIAN = 10037;//骑宠加点

    public static string GetFuncNameById(int functionid)
    {
        string functionname = "功能" + functionid;
        switch (functionid)
        {
            case RENWU: functionname = "任务"; break;
            case DUIWU: functionname = "队伍"; break;
            case HUODONG: functionname = "活动"; break;
            case JINGJICHANG: functionname = "竞技场"; break;
            case JIUGUAN: functionname = "酒馆"; break;
            case KEJU: functionname = "朝云科举"; break;
            case XITONG: functionname = "系统"; break;
            case PETSTORE: functionname = "宠物商店"; break;
            case SHANGHUI: functionname = "商会"; break;
            case PAIMAIHANG: functionname = "拍卖行"; break;
            case CHONGZHI: functionname = "充值"; break;
            case WUXING: functionname = "悟性"; break;
            case BEIBAO: functionname = "背包"; break;
            case XINFAJINENG: functionname = "心法技能"; break;
            case BANGPAI: functionname = LangConstant.BANGPAI; break;
            case HUOBAN: functionname = "伙伴"; break;
            case ZHENXING: functionname = "阵型"; break;
            case PAIHANG: functionname = "排行榜"; break;
            case DAZAO: functionname = "打造"; break;
            case SHENGXING: functionname = "升星"; break;
            case XIANGQIAN: functionname = "宝石镶嵌"; break;
            case HECHENG: functionname = "宝石合成"; break;
            case QIANGHUA: functionname = "强化"; break;
            case FENJIE: functionname = "分解"; break;
            case CHONGZHU: functionname = "重铸"; break;
            case XILIAN: functionname = "炼化"; break;
            case GUANZHU: functionname = "灌注"; break;
            case CHUANCHENG: functionname = "传承"; break;
            case QIANDAO: functionname = "每日签到"; break;
            case DENGLUJIANGLI: functionname = "登陆奖励"; break;
            case ZAIXIANJIANGLI: functionname = "在线奖励"; break;
            case YOUJIAN: functionname = "邮件"; break;
            case HAOYOU: functionname = "好友"; break;
            case CHENGJIU: functionname = "成就"; break;
            case TISHENG: functionname = "提升"; break;
            case GMBUCHANG: functionname = "GM补偿"; break;
            case SHENMISHOP: functionname = "神秘商店"; break;
            case JINGCAIHUODONG: functionname = "精彩活动"; break;
            case VIP: functionname = "VIP"; break;
            case JINJUANTAOCAN: functionname = "金卷套餐"; break;
            case ZAIXIANLIBAO: functionname = "特殊在线礼包"; break;
            case QICHONG: functionname = "骑宠"; break;
            case CAIKUANG: functionname = "采矿"; break;
            case CHUBAOANLIANG: functionname = "除暴安良"; break;
            case LVYEXIANZONG: functionname = "绿野仙踪"; break;
            case BAOTU: functionname = "宝图任务"; break;
            case YUNLIANG: functionname = "护送粮草"; break;
            case SHITU: functionname = "师徒"; break;
            case HUNYIN: functionname = "婚姻"; break;
            case NVSN: functionname = "NvsN联赛"; break;
            case CORPSTASK: functionname = "帮派任务"; break;
            case DUIHUANJIANGLI:functionname = "兑换奖励";break;
            case TOWER: functionname = "通天塔"; break;
            case PUTONGMOZU: functionname = "魔族副本"; break;
            case KUNNANMOZU: functionname = "魔族副本-困难"; break;

            /*-----以下功能客户端独有-----*/
            case JIANGLI: functionname = "奖励"; break;
            case PETSINFO: functionname = "宠物信息"; break;
            case ROLEINFO: functionname = "人物信息"; break;
            case WORLDMAP: functionname = "世界地图"; break;
            case LVYEXIANZONG_DANREN: functionname = "绿野仙踪（单人）"; break;
            case LVYEXIANZONG_ZUDUI: functionname = "绿野仙踪（组队）"; break;
            case CHENGHAO: functionname = "称号"; break;
            case BPJS_Enter: functionname = "进入帮派竞赛"; break;
            case BPJS_Paihang: functionname = "帮派排行"; break;
            case SHITU_SHOUTU: functionname = "收徒"; break;
            case SHITU_CHUSHI: functionname = "出师"; break;
            case SHITU_JIECHU: functionname = "解除师徒关系"; break;
            case JIEHUN_WE: functionname = "我要结婚"; break;
            case LIHUN_WE: functionname = "我要离婚"; break;
            case CHONGWUDAO_YI: functionname = "宠物岛一层(30级)"; break;
            case CHONGWUDAO_ER: functionname = "宠物岛二层(45级)"; break;
            case CHONGWUDAO_SAN: functionname = "宠物岛三层(60级)"; break;
            case CHONGWUDAO_SI: functionname = "宠物岛四层"; break;
            case TOWER_BEAST:functionname = "查看最优击杀";break;
            case TOWER_EARLIEST:functionname = "查看最早击杀"; break;
            case CORPSBOSS_CHANLLGE: functionname = "挑战帮派Boss"; break;
            case CORPSBOSS_BEAST: functionname = "查看帮派最高击杀"; break;
            case CANGKU: functionname = "仓库"; break;
            case BANGPAIFUZHU: functionname = "辅助技能"; break;
            case BANGPAIXIULIAN: functionname = "修炼技能"; break;
            case DANRENFUBEN: functionname = "剧情副本"; break;
            case XIAN_HU_ZUORI: functionname = "祈福仙葫昨日奖励"; break;
            case LING_XI_XIANHU_ZUORI: functionname = "灵犀仙葫昨日奖励"; break;
            case LING_XI_XIANHU_SHANGZHOU: functionname = "灵犀仙葫上周奖励"; break;
            case XIANHU: functionname = "仙葫"; break;
            case NEWGUAJI: functionname = "野外挂机"; break;
            case SHENGHUOJINENG: functionname = "生活技能"; break;
            case SHENGHUOJINENG_STORE: functionname = "生活技能书商店"; break;
            case YUEKA: functionname = "月卡"; break;
            case RINGTASK: functionname = "环任务"; break;
            default:
                break;
        }
        return functionname;
    }

}
