package com.imop.lj.gameserver.marry.msg;

import java.util.HashMap;
import java.util.Map;

import com.imop.lj.core.msg.MessageType;
import com.imop.lj.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class MarryMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_FIRST_MARRY, CGFirstMarry.class);
		map.put(MessageType.CG_MARRY, CGMarry.class);
		map.put(MessageType.CG_MARRY_INFO, CGMarryInfo.class);
		map.put(MessageType.CG_FIRST_FIRE_MARRY, CGFirstFireMarry.class);
		map.put(MessageType.CG_FIRE_MARRY, CGFireMarry.class);
		map.put(MessageType.CG_FORCE_FIRE_MARRY, CGForceFireMarry.class);
		return map;
	}

}
