package com.imop.lj.gameserver.foragetask.msg;

import java.util.HashMap;
import java.util.Map;

import com.imop.lj.core.msg.MessageType;
import com.imop.lj.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class ForagetaskMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_OPEN_FORAGETASK_PANEL, CGOpenForagetaskPanel.class);
		map.put(MessageType.CG_FORAGETASK_ACCEPT, CGForagetaskAccept.class);
		map.put(MessageType.CG_GIVE_UP_FORAGETASK, CGGiveUpForagetask.class);
		map.put(MessageType.CG_FINISH_FORAGETASK, CGFinishForagetask.class);
		map.put(MessageType.CG_FORAGETASK_REFRESH, CGForagetaskRefresh.class);
		return map;
	}

}
