package com.imop.lj.gameserver.quest.msg;

import java.util.HashMap;
import java.util.Map;

import com.imop.lj.core.msg.MessageType;
import com.imop.lj.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class QuestMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_COMMON_QUEST_LIST, CGCommonQuestList.class);
		map.put(MessageType.CG_ACCEPT_QUEST, CGAcceptQuest.class);
		map.put(MessageType.CG_GIVE_UP_QUEST, CGGiveUpQuest.class);
		map.put(MessageType.CG_FINISH_QUEST, CGFinishQuest.class);
		return map;
	}

}
