public class ViewConst{
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Card_Fly = "Card_Fly.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Energy = "Energy.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_FX_Hint_2 = "FX_Hint_2.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Level_Fly = "Level_Fly.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_PlayBtn_Glow = "PlayBtn_Glow.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Video_Glow = "Video_Glow.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Web_Fly = "Web_Fly.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_win_Fly = "win_Fly.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_AudioData = "AudioData.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Block_Entertainment = "Block_Entertainment.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Block_Geography = "Block_Geography.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Block_History = "Block_History.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Block_Language = "Block_Language.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Block_Lifestyle = "Block_Lifestyle.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Block_Science = "Block_Science.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CardPieces_CircleFour = "CardPieces_CircleFour.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CardPieces_Five = "CardPieces_Five.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CardPieces_Four = "CardPieces_Four.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CardPieces_One = "CardPieces_One.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CardPieces_Six = "CardPieces_Six.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CardPieces_Three = "CardPieces_Three.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CardPieces_Two = "CardPieces_Two.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_ClassicWinDialog = "ClassicWinDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CrossWinDialog = "CrossWinDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_DailyWinDialog = "DailyWinDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CupProgress = "CupProgress.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CupReward = "CupReward.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Box_7Days_Big = "Box_7Days_Big.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Box_7Days_Small = "Box_7Days_Small.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Box_LevelRewards = "Box_LevelRewards.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Box_Store_01 = "Box_Store_01.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Box_Store_02 = "Box_Store_02.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Box_Store_03 = "Box_Store_03.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Box_Store_04 = "Box_Store_04.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Box_Store_500more = "Box_Store_500more.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Box_WebRewards = "Box_WebRewards.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CommonRewardDialog = "CommonRewardDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CommonRewardItem = "CommonRewardItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_BuyCancelDialog = "BuyCancelDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CloseBtn_Small = "CloseBtn_Small.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CommonBtn = "CommonBtn.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CommonGiftDialog = "CommonGiftDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CupRewardDialog = "CupRewardDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_DailyEnterGuideDialog = "DailyEnterGuideDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Gift = "Gift.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_LevelRewardDialog = "LevelRewardDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_PromoteVideoDialog = "PromoteVideoDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_QuestionRestDialog = "QuestionRestDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Quit_Panel = "Quit_Panel.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_RewardVideoDialog = "RewardVideoDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_WellDownDialog = "WellDownDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_DailyChallengeEventDialog = "DailyChallengeEventDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_DailyChallengeWheelDialog = "DailyChallengeWheelDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_DailyRuleDialog = "DailyRuleDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_DailyUnlockRewardDialog = "DailyUnlockRewardDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_NetConnectFailDialog = "NetConnectFailDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_NotConnectTips = "NotConnectTips.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_AdWaitDialog = "AdWaitDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_PrivacyPolicyDialog = "PrivacyPolicyDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_ShopWaitDialog = "ShopWaitDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_VideoGiftDialog = "VideoGiftDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_WaitDialog = "WaitDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_EliteLevelContinueDialog = "EliteLevelContinueDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_EliteLevelStartDialog = "EliteLevelStartDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_EliteLevelUnlockDialog = "EliteLevelUnlockDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_EmailDeleteMessageDialog = "EmailDeleteMessageDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_EmailGiftDialog = "EmailGiftDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_EmailItem = "EmailItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_EmaliSliderDialog = "EmaliSliderDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Encourage_Bright = "Encourage_Bright.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Encourage_Cool = "Encourage_Cool.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Encourage_Fantastic = "Encourage_Fantastic.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Encourage_Good = "Encourage_Good.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Encourage_Perfect = "Encourage_Perfect.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Encourage_Smart = "Encourage_Smart.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Encourage_Wonderful = "Encourage_Wonderful.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Encourage_Wow = "Encourage_Wow.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_FbConnectSuccessDialog = "FbConnectSuccessDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_FBLoginFailDialog = "FBLoginFailDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_FBLoginGiftDialog = "FBLoginGiftDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_FBLogOutDialog = "FBLogOutDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_FBSignInDialog = "FBSignInDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_GameLoadingWindow = "GameLoadingWindow.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_BookBuddiesDialog = "BookBuddiesDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_HowToPlayDialog = "HowToPlayDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CardFansTips = "CardFansTips.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Collect_WordMaster_Flag_Item = "Collect_WordMaster_Flag_Item.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Collect_WordMaster_Item = "Collect_WordMaster_Item.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Collect_WordMaster_Pets_Item = "Collect_WordMaster_Pets_Item.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_DecorationDialog = "DecorationDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Heart_Fly = "Heart_Fly.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_KnowledgeCardDialog = "KnowledgeCardDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_PetsDialog = "PetsDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_PetShowItem = "PetShowItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_PetsItem = "PetsItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_ShowPetDialog = "ShowPetDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_ShowTitleDialog = "ShowTitleDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_TipRewatdItem = "TipRewatdItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_tips = "tips.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_TitleItem = "TitleItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_TitleShowItem = "TitleShowItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_BlueStarFly = "BlueStarFly.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_BookItem = "BookItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_HappinessItem = "HappinessItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_HappinessSelectLevelDialog = "HappinessSelectLevelDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_MagazineBookItem = "MagazineBookItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_MagazineListDialog = "MagazineListDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_wm_ano_egy = "wm_ano_egy.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_wm_bas_egy = "wm_bas_egy.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_wm_chi_pet = "wm_chi_pet.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_wm_cla_egy = "wm_cla_egy.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_wm_com_egy = "wm_com_egy.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_wm_ind_wil = "wm_ind_wil.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_wm_let_wil = "wm_let_wil.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_wm_lex_wil = "wm_lex_wil.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_wm_phr_egy = "wm_phr_egy.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_wm_suf_egy = "wm_suf_egy.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_wm_wor_wil = "wm_wor_wil.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_AnswerImageGui = "AnswerImageGui.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_BeeHomeBtnGui = "BeeHomeBtnGui.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_BeeInGameGui = "BeeInGameGui.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_BlogEnterGui = "BlogEnterGui.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_DailyEntranceGui = "DailyEntranceGui.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_DailyNoviceGui = "DailyNoviceGui.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_FirstWordGui = "FirstWordGui.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_HintPropGui = "HintPropGui.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_PageTurningGui = "PageTurningGui.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_PassFirstWordGui = "PassFirstWordGui.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_PlayWordRewardCoinGui = "PlayWordRewardCoinGui.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_PlayWordRewardCoinGui2 = "PlayWordRewardCoinGui2.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_PrepositionWordGui = "PrepositionWordGui.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_VoiceWordGui1 = "VoiceWordGui1.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_VoiceWordGui2 = "VoiceWordGui2.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_VoiceWordGui3 = "VoiceWordGui3.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_WelcomeGui = "WelcomeGui.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Deals_Item = "Deals_Item.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Promotion_NewPlayer_Dialog = "Promotion_NewPlayer_Dialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Promotion_Normal_Dialog = "Promotion_Normal_Dialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_RemoveAdSuccessDialog = "RemoveAdSuccessDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_RestoreButton = "RestoreButton.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Shop500_Limited_Time_Item = "Shop500_Limited_Time_Item.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_ShopLimitBagOneDialog = "ShopLimitBagOneDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_ShopLimitBagTwoDialog = "ShopLimitBagTwoDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_ShopNoAdsItem = "ShopNoAdsItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_ShopRemoveAdsDialog = "ShopRemoveAdsDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_ShopSuccessDialog = "ShopSuccessDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Shop_Remove_Ads_Item = "Shop_Remove_Ads_Item.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Shop_Super_Bee_Item = "Shop_Super_Bee_Item.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Shop_Super_Limit_Five_Item = "Shop_Super_Limit_Five_Item.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Shop_Super_Limit_Four_Item = "Shop_Super_Limit_Four_Item.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Shop_Super_Limit_One_Item = "Shop_Super_Limit_One_Item.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Shop_Super_Limit_Three_Item = "Shop_Super_Limit_Three_Item.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Shop_Super_Limit_Two_Item = "Shop_Super_Limit_Two_Item.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_Shop_Super_Started_Item = "Shop_Super_Started_Item.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_StoreDialog = "StoreDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_PushContinueDialog = "PushContinueDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_PushDialog = "PushDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_PushDisAbleDialog = "PushDisAbleDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_OldRateDialog = "OldRateDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_BeeFly = "BeeFly.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_coinFly = "coinFly.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CupFly = "CupFly.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_ExpFly = "ExpFly.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_FlyStar = "FlyStar.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_RubyFly = "RubyFly.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_RubyFly_3d = "RubyFly_3d.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_RubyFly_boom = "RubyFly_boom.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_singleAcIconFly = "singleAcIconFly.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_singlecoinFly = "singlecoinFly.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_StarFly = "StarFly.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_ClassicSettingDialog = "ClassicSettingDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CrazeSettingPanel = "CrazeSettingPanel.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_SignDayItem = "SignDayItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_SignDialog = "SignDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_FBPermissionDialog = "FBPermissionDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_FeedBackItem = "FeedBackItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_feedbackSendDialog = "feedbackSendDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_feedbackSuccessDialog = "feedbackSuccessDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_SpineMecanim_Guide_Ann_Ani = "SpineMecanim_Guide_Ann_Ani.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_ActivityTheme = "ActivityTheme.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_CrossCrazeItem = "CrossCrazeItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_EventItem = "EventItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_EventRankItem = "EventRankItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_DecorationTheme = "DecorationTheme.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_TitlesViewItem = "TitlesViewItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_HomeTheme = "HomeTheme.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_NewFloatWeekendRankItem = "NewFloatWeekendRankItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_NewWeekendRankItem = "NewWeekendRankItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_NewWeekendRankWinDialog = "NewWeekendRankWinDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_RankTheme = "RankTheme.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_ShopTheme = "ShopTheme.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_ToastWindow = "ToastWindow.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_FloatWeekendRankItem = "FloatWeekendRankItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_FRStar = "FRStar.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_FRStar_Boom = "FRStar_Boom.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_WeekActivityHead = "WeekActivityHead.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_WeekendPropagandaDialog = "WeekendPropagandaDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_WeekendRankItem = "WeekendRankItem.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_WeekRankListDialog = "WeekRankListDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_EpisodeUnlockDialog = "EpisodeUnlockDialog.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_WorldComingSoon = "WorldComingSoon.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_WorldMap = "WorldMap.prefab";
//Group：PackTogetherByLabel ;Label:prefab;
     public const string prefab_WorldMapItem = "WorldMapItem.prefab";
//Group：PackTogetherByLabel ;Label:png;
     public const string png_Gift_Bee = "Gift_Bee.png";
//Group：PackTogetherByLabel ;Label:png;
     public const string png_Gift_Bee_g = "Gift_Bee_g.png";
//Group：PackTogetherByLabel ;Label:png;
     public const string png_Gift_Coin = "Gift_Coin.png";
//Group：PackTogetherByLabel ;Label:png;
     public const string png_Gift_Hint_1 = "Gift_Hint_1.png";
//Group：PackTogetherByLabel ;Label:png;
     public const string png_Gift_Hint_2 = "Gift_Hint_2.png";
//Group：PackTogetherByLabel ;Label:png;
     public const string png_Gift_Hint_3 = "Gift_Hint_3.png";
//Group：PackTogetherByLabel ;Label:png;
     public const string png_Gift_Hint_4 = "Gift_Hint_4.png";
//Group：PackTogetherByLabel ;Label:png;
     public const string png_Gift_Hint_5 = "Gift_Hint_5.png";
//Group：PackTogetherByLabel ;Label:png;
     public const string png_Play_Coin_g = "Play_Coin_g.png";
//Group：PackTogetherByLabel ;Label:png;
     public const string png_Play_Hint1_g = "Play_Hint1_g.png";
//Group：PackTogetherByLabel ;Label:png;
     public const string png_Play_Hint2_g = "Play_Hint2_g.png";
//Group：PackTogetherByLabel ;Label:png;
     public const string png_Play_Hint3_g = "Play_Hint3_g.png";
//Group：PackTogetherByLabel ;Label:png;
     public const string png_Play_Hint4_g = "Play_Hint4_g.png";
//Group：PackTogetherByLabel ;Label:png;
     public const string png_pet_Popup_up_theme1_bg = "pet_Popup_up_theme1_bg.png";
//Group：PackTogetherByLabel ;Label:png;
     public const string png_pet_Popup_up_theme1_logo = "pet_Popup_up_theme1_logo.png";
//Group：PackTogetherByLabel ;Label:png;
     public const string png_pet_Popup_up_theme2_bg = "pet_Popup_up_theme2_bg.png";
//Group：PackTogetherByLabel ;Label:png;
     public const string png_pet_Popup_up_theme2_logo = "pet_Popup_up_theme2_logo.png";
//Group：PackTogetherByLabel ;Label:txt;
     public const string txt_AddressablesRules = "AddressablesRules.txt";
//Group：PackTogetherByLabel ;Label:txt;
     public const string txt_addressAssetsConfig = "addressAssetsConfig.txt";
//Group：PackTogetherByLabel ;Label:txt;
     public const string txt_Manifest = "Manifest.txt";
//Group：PackTogetherByLabel ;Label:txt;
     public const string txt_Rules = "Rules.txt";
//Group：PackTogetherByLabel ;Label:txt;
     public const string atlas_wm_ano_egy = "wm_ano_egy.atlas.txt";
//Group：PackTogetherByLabel ;Label:txt;
     public const string atlas_wm_bas_egy = "wm_bas_egy.atlas.txt";
//Group：PackTogetherByLabel ;Label:txt;
     public const string atlas_wm_chi_pet = "wm_chi_pet.atlas.txt";
//Group：PackTogetherByLabel ;Label:txt;
     public const string atlas_wm_cla_egy = "wm_cla_egy.atlas.txt";
//Group：PackTogetherByLabel ;Label:txt;
     public const string atlas_wm_com_egy = "wm_com_egy.atlas.txt";
//Group：PackTogetherByLabel ;Label:txt;
     public const string atlas_wm_ind_wil = "wm_ind_wil.atlas.txt";
//Group：PackTogetherByLabel ;Label:txt;
     public const string atlas_wm_let_wil = "wm_let_wil.atlas.txt";
//Group：PackTogetherByLabel ;Label:txt;
     public const string atlas_wm_lex_wil = "wm_lex_wil.atlas.txt";
//Group：PackTogetherByLabel ;Label:txt;
     public const string atlas_wm_phr_egy = "wm_phr_egy.atlas.txt";
//Group：PackTogetherByLabel ;Label:txt;
     public const string atlas_wm_suf_egy = "wm_suf_egy.atlas.txt";
//Group：PackTogetherByLabel ;Label:txt;
     public const string atlas_wm_wor_wil = "wm_wor_wil.atlas.txt";
//Group：PackTogetherByLabel ;Label:txt;
     public const string atlas_Bee_Ani = "Bee_Ani.atlas.txt";
//Group：PackTogetherByLabel ;Label:txt;
     public const string atlas_Guide_Ann = "Guide_Ann.atlas.txt";
//Group：PackTogetherByLabel ;Label:txt;
     public const string atlas_Wiki_Ani = "Wiki_Ani.atlas.txt";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_DailyWin = "DailyWin.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_NewPetAppear = "NewPetAppear.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_petFlyFinish = "petFlyFinish.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_window_pet_unlock = "window_pet_unlock.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_clickwordcell = "clickwordcell.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_coinAppear = "coinAppear.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_PartRight = "PartRight.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_WordRight = "WordRight.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_wordWrong = "wordWrong.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_beeAppear = "beeAppear.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_beeHint = "beeHint.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_hint2 = "hint2.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_hintfocuson = "hintfocuson.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_airfly = "airfly.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_blog_itemclick = "blog_itemclick.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_btn_home = "btn_home.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_btn_normal = "btn_normal.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_dailypetgetFly = "dailypetgetFly.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_daily_petget = "daily_petget.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_DownHeart = "DownHeart.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_Downkey = "Downkey.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_flash_unlock = "flash_unlock.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_flyblog_down = "flyblog_down.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_flyHeart = "flyHeart.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_flyKey = "flyKey.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_fly_blog = "fly_blog.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_getcoin = "getcoin.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_gift_boxdown = "gift_boxdown.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_gift_itemappear = "gift_itemappear.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_gift_item_pop = "gift_item_pop.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_panel_close = "panel_close.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_panel_show = "panel_show.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_ShopRewardMusic = "ShopRewardMusic.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_sign_box_out = "sign_box_out.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_sign_paper = "sign_paper.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_tip_appear = "tip_appear.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_unlockWorld = "unlockWorld.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_0_calcel = "0_calcel.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_a = "a.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_b = "b.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_c = "c.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_d = "d.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_e = "e.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_f = "f.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_g = "g.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_h = "h.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_i = "i.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_j = "j.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_k = "k.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_l = "l.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_m = "m.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_n = "n.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_o = "o.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_p = "p.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_q = "q.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_r = "r.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_s = "s.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_t = "t.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_u = "u.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_v = "v.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_w = "w.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_x = "x.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_y = "y.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_z = "z.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_voicefail = "voicefail.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_voicefly = "voicefly.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_voicefly0 = "voicefly0.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_voiceright = "voiceright.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_voicewakeup = "voicewakeup.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_welldone_h = "welldone_h.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string wav_welldone_normal = "welldone_normal.wav";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_Daily_addpower = "Daily_addpower.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_Daily_star_appear = "Daily_star_appear.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_Daily_wheel_onepart = "Daily_wheel_onepart.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_Daily_wheel_run = "Daily_wheel_run.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_AutoHintFill = "AutoHintFill.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_clicklockhint = "clicklockhint.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_frstarDown = "frstarDown.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_PicBoxOpen = "PicBoxOpen.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_right_left = "right_left.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_hint1 = "hint1.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_hint3 = "hint3.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_hint4 = "hint4.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_petclick = "petclick.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_EquipPet = "EquipPet.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_GiftDialog = "GiftDialog.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_home_frstareffect = "home_frstareffect.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_level_btn_addNum = "level_btn_addNum.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_loadingFly = "loadingFly.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_subBoxOpen = "subBoxOpen.ogg";
//Group：PackTogetherByLabel ;Label:sound;
     public const string ogg_win_fall = "win_fall.ogg";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_AdsConfig_AndroidA = "AdsConfig_AndroidA.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_AdsConfig_IosA = "AdsConfig_IosA.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_AdsConfig_IosB = "AdsConfig_IosB.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_AnswerTips_AnswerTip = "AnswerTips_AnswerTip.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_BagItems_ItemReward = "BagItems_ItemReward.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_CommConfig_config = "CommConfig_config.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_DailyRewardAB_Android_ItemReward_A = "DailyRewardAB_Android_ItemReward_A.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_DailyRewardAB_Android_ItemReward_B = "DailyRewardAB_Android_ItemReward_B.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_DailyRewardAB_Ios_ItemReward_A = "DailyRewardAB_Ios_ItemReward_A.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_DailyRewardAB_Ios_ItemReward_B = "DailyRewardAB_Ios_ItemReward_B.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_EN_Google_Sheets = "EN_Google_Sheets.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_IapProductConfig_AndroidA = "IapProductConfig_AndroidA.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_IapProductConfig_IosA = "IapProductConfig_IosA.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_LanguageConfig_EnConfig = "LanguageConfig_EnConfig.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_NameConfig_boys = "NameConfig_boys.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_NameConfig_girls = "NameConfig_girls.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_Pets_Pet = "Pets_Pet.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_PetTipsList_TipList = "PetTipsList_TipList.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_PlayerSign_Sign = "PlayerSign_Sign.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_ProbabilityPool_ProbabilityPool = "ProbabilityPool_ProbabilityPool.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_PropertyAB_Android_Prop_A = "PropertyAB_Android_Prop_A.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_PropertyAB_Android_Prop_B = "PropertyAB_Android_Prop_B.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_PropertyAB_Ios_Prop_A = "PropertyAB_Ios_Prop_A.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_PropertyAB_Ios_Prop_B = "PropertyAB_Ios_Prop_B.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_RateConfig_RateConfig = "RateConfig_RateConfig.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_RateReward_rate = "RateReward_rate.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_RewardAB_Android_Reward_A = "RewardAB_Android_Reward_A.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_RewardAB_Android_Reward_B = "RewardAB_Android_Reward_B.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_RewardAB_Ios_Reward_A = "RewardAB_Ios_Reward_A.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_RewardAB_Ios_Reward_B = "RewardAB_Ios_Reward_B.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_SubwordRewardTable_Table = "SubwordRewardTable_Table.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_UserGuide_Guide = "UserGuide_Guide.asset";
//Group：PackTogetherByLabel ;Label:preloadAsset;
     public const string asset_WebBox_ProbabilityPool = "WebBox_ProbabilityPool.asset";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_BeeCountBar = "BeeCountBar.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_ClassicCell = "ClassicCell.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_ClassicCells = "ClassicCells.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_ClassicGame = "ClassicGame.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_ClassicQuestionDisplay = "ClassicQuestionDisplay.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_ClassicSkills = "ClassicSkills.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_ClassicStatusBar = "ClassicStatusBar.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_ClassRate = "ClassRate.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_ClassVoice = "ClassVoice.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_ClassVoiceLetter = "ClassVoiceLetter.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_Keyboard = "Keyboard.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_KeyboardCellFly = "KeyboardCellFly.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_PictureBox = "PictureBox.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_PicWordFlag = "PicWordFlag.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_RateCell = "RateCell.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_WordSpit = "WordSpit.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_ChallengeRabbit = "ChallengeRabbit.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_CommonNotice = "CommonNotice.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_CommonNotice_Level = "CommonNotice_Level.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_DailyNotice = "DailyNotice.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_HintNotice = "HintNotice.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_KnowledgeCardItem = "KnowledgeCardItem.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_Letter = "Letter.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_MasterHead = "MasterHead.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_VoiceErrorTips = "VoiceErrorTips.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_VoiceNotice = "VoiceNotice.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_CrossCell = "CrossCell.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_CrossCells = "CrossCells.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_CrossGame = "CrossGame.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_CrossPictureBox = "CrossPictureBox.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_CrossQuestionDisplay = "CrossQuestionDisplay.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_CrossSkills = "CrossSkills.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_CrossStatusBar = "CrossStatusBar.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_DailyCell = "DailyCell.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_DailyCells = "DailyCells.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_DailyGame = "DailyGame.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_DailyQuestionDisplay = "DailyQuestionDisplay.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_DailySkills = "DailySkills.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_DailyStatusBar = "DailyStatusBar.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_FRClassicCells = "FRClassicCells.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_FRClassicGame = "FRClassicGame.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_FRClassicStatusBar = "FRClassicStatusBar.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_OneWordCell = "OneWordCell.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_OneWordCells = "OneWordCells.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_OneWordGame = "OneWordGame.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_OneWordQuestionDisplay = "OneWordQuestionDisplay.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_OneWordRewardDialog = "OneWordRewardDialog.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_OneWordRewardVideo = "OneWordRewardVideo.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_OneWordSkills = "OneWordSkills.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_OneWordStatusBar = "OneWordStatusBar.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_PadFRClassicCells = "PadFRClassicCells.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_PadFRClassicGame = "PadFRClassicGame.prefab";
//Group：PackTogetherByLabel ;Label:preloadPrefab;
     public const string prefab_PadFRClassicStatusBar = "PadFRClassicStatusBar.prefab";
//Group：PackSeparately ;Label:BG;
     public const string jpg_departures_home = "departures_home.jpg";
//Group：PackSeparately ;Label:BG;
     public const string jpg_egypt_home = "egypt_home.jpg";
//Group：PackSeparately ;Label:BG;
     public const string jpg_australia_map_locked = "australia_map_locked.jpg";
//Group：PackSeparately ;Label:BG;
     public const string jpg_brazil_map_locked = "brazil_map_locked.jpg";
//Group：PackSeparately ;Label:BG;
     public const string jpg_departures_map_locked = "departures_map_locked.jpg";
//Group：PackSeparately ;Label:BG;
     public const string jpg_departures_map_unlock = "departures_map_unlock.jpg";
//Group：PackSeparately ;Label:BG;
     public const string jpg_egypt_map_locked = "egypt_map_locked.jpg";
//Group：PackSeparately ;Label:BG;
     public const string jpg_egypt_map_unlock = "egypt_map_unlock.jpg";
//Group：PackSeparately ;Label:BG;
     public const string jpg_england_map_locked = "england_map_locked.jpg";
//Group：PackSeparately ;Label:BG;
     public const string jpg_france_map_locked = "france_map_locked.jpg";
//Group：PackSeparately ;Label:BG;
     public const string jpg_greece_map_locked = "greece_map_locked.jpg";
//Group：PackSeparately ;Label:BG;
     public const string jpg_japan_map_locked = "japan_map_locked.jpg";
//Group：PackSeparately ;Label:BG;
     public const string jpg_korea_map_locked = "korea_map_locked.jpg";
//Group：PackSeparately ;Label:BG;
     public const string jpg_mexico_map_locked = "mexico_map_locked.jpg";
//Group：PackSeparately ;Label:BG;
     public const string jpg_morocco_map_locked = "morocco_map_locked.jpg";
//Group：PackSeparately ;Label:BG;
     public const string jpg_russia_map_locked = "russia_map_locked.jpg";
//Group：PackSeparately ;Label:BG;
     public const string jpg_sweden_map_locked = "sweden_map_locked.jpg";
//Group：PackSeparately ;Label:BG;
     public const string jpg_thailand_map_locked = "thailand_map_locked.jpg";
//Group：PackSeparately ;Label:Map;
     public const string asset_Android_StoryConfigA = "Android_StoryConfigA.asset";
//Group：PackSeparately ;Label:Map;
     public const string asset_Android_StoryConfigB = "Android_StoryConfigB.asset";
//Group：PackSeparately ;Label:Map;
     public const string asset_Ios_StoryConfig = "Ios_StoryConfig.asset";
//Group：PackTogetherByLabel ;Label:bgm;
     public const string mp3_common_gm = "common_gm.mp3";
//Group：PackTogetherByLabel ;Label:bgm;
     public const string mp3_common_hm = "common_hm.mp3";
//Group：Scene ;Label:Scene;
     public const string unity_Main = "Main.unity";
//Group：Scene ;Label:Scene;
     public const string unity_TestScene = "TestScene.unity";
//Group：PackTogetherByLabel ;Label:#;
     public const string spriteatlas_Letters = "Letters.spriteatlas";
//Group：PackTogetherByLabel ;Label:#;
     public const string spriteatlas_A_Common = "A_Common.spriteatlas";
//Group：PackTogetherByLabel ;Label:#;
     public const string spriteatlas_A_Daily = "A_Daily.spriteatlas";
//Group：PackTogetherByLabel ;Label:#;
     public const string spriteatlas_A_KnowCard = "A_KnowCard.spriteatlas";
//Group：PackTogetherByLabel ;Label:#;
     public const string spriteatlas_A_Play = "A_Play.spriteatlas";
//Group：PackTogetherByLabel ;Label:#;
     public const string spriteatlas_A_Shop = "A_Shop.spriteatlas";
//Group：PackTogetherByLabel ;Label:#;
     public const string spriteatlas_Weekend_Activity = "Weekend_Activity.spriteatlas";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Buttonclickani = "Buttonclickani.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Button_Press_QBtn = "Button_Press_QBtn.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_coinanimation = "coinanimation.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_RubyBalance_coinyituo_Ani = "RubyBalance_coinyituo_Ani.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_RubyBalance_Promotion_Ani = "RubyBalance_Promotion_Ani.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_TipsLong_Ani = "TipsLong_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_TipsLong_In = "TipsLong_In.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_TipsLong_Out = "TipsLong_Out.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_7Days_Ani = "7Days_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_7Days_Today_go_yesterday = "7Days_Today_go_yesterday.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_7Days_Today_Idle = "7Days_Today_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_7Days_Today_Idle_Now = "7Days_Today_Idle_Now.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_7Days_Tomorrow_go_today = "7Days_Tomorrow_go_today.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_7Days_Tomorrow_Idle = "7Days_Tomorrow_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_7Days_yesterday_Idle = "7Days_yesterday_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_AD_Fly_Ani = "AD_Fly_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_AD_Fly_Idle = "AD_Fly_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Correct_A = "Correct_A.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Correct_Ani = "Correct_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_DailyGetStar_1 = "DailyGetStar_1.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_DailyGetStar_2 = "DailyGetStar_2.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_DailyGetStar_3 = "DailyGetStar_3.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_DailyGetStar_4 = "DailyGetStar_4.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_DailyGetStar_Ani = "DailyGetStar_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_DailyGetStar_Idle = "DailyGetStar_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Daily_block_Ani = "Daily_block_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Daily_block_Finish = "Daily_block_Finish.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Daily_block_Lock_Idle = "Daily_block_Lock_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Daily_block_Lock_to_Unlock = "Daily_block_Lock_to_Unlock.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Daily_block_Unlock = "Daily_block_Unlock.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Daily_block_Unlock_to_Finish = "Daily_block_Unlock_to_Finish.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Date_Ani = "Date_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Date_Idle = "Date_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Date_Next = "Date_Next.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_EpisodeUnlock_Ani = "EpisodeUnlock_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_EpisodeUnlock_Appear = "EpisodeUnlock_Appear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_EpisodeUnlock_DisAppear = "EpisodeUnlock_DisAppear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_FlashCraze_Ani = "FlashCraze_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_FlashCraze_Now = "FlashCraze_Now.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_FlashCraze_Wait = "FlashCraze_Wait.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Fly_Card_Ani = "Fly_Card_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Fly_Card_Appear = "Fly_Card_Appear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Fly_Level_Ani = "Fly_Level_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Fly_Level_Appear = "Fly_Level_Appear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Fly_Web_Ani = "Fly_Web_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Fly_Web_Appear = "Fly_Web_Appear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_FrameFlash_Ani = "FrameFlash_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_FrameFlash_Appear = "FrameFlash_Appear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Guide_Hand_Ani = "Guide_Hand_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Guide_Hand_Loop = "Guide_Hand_Loop.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Guide_Que_Ani = "Guide_Que_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Guide_Que_Loop = "Guide_Que_Loop.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Hint2CellFly_Ani = "Hint2CellFly_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Hint2CellFly_Idle = "Hint2CellFly_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Hint_1_Ani = "Hint_1_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Hint_1_Appear = "Hint_1_Appear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Hint_1_Idle = "Hint_1_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Hint_2_Ani = "Hint_2_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Hint_2_Appear = "Hint_2_Appear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Hint_2_Idle = "Hint_2_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Hint_3_Ani = "Hint_3_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Hint_3_Appear = "Hint_3_Appear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Hint_3_Idle = "Hint_3_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Hint_4_Ani = "Hint_4_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Hint_4_Appear = "Hint_4_Appear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_KnowledgeCard_Ani = "KnowledgeCard_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_KnowledgeCard_Appear = "KnowledgeCard_Appear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_KnowledgeCard_Disappear = "KnowledgeCard_Disappear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_LetterEffect_Ani = "LetterEffect_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_LetterEffect_Down = "LetterEffect_Down.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Level_Re_Ani = "Level_Re_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Level_Re_Full = "Level_Re_Full.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Level_Re_Hit = "Level_Re_Hit.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Level_Re_Idle = "Level_Re_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_MoreOffer_Ani = "MoreOffer_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_MoreOffer_In = "MoreOffer_In.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_NextLevel_Ani = "NextLevel_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_NextLevel_Idle = "NextLevel_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_NextLevel_Next = "NextLevel_Next.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_OneWord_Lock_Ani = "OneWord_Lock_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_OneWord_Lock_Idle = "OneWord_Lock_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_OneWord_Lock_Unlock = "OneWord_Lock_Unlock.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_OtherCellTips_Ani = "OtherCellTips_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_OtherCellTips_Idle = "OtherCellTips_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Rewards_Item_Ani = "Rewards_Item_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Item_Box_Appear = "Rewards_Item_Box_Appear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Item_Common_Appear = "Rewards_Item_Common_Appear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Item_Idle = "Rewards_Item_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Tips_Ani = "Tips_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Tips_Idle = "Tips_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Tips_Long_Idle = "Tips_Long_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Tips_Out = "Tips_Out.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Turn_Box = "Turn_Box.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Turn_Box_idle = "Turn_Box_idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Turn_Common = "Turn_Common.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Turn_Common_Idle = "Turn_Common_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Web_Re_Ani = "Web_Re_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Web_Re_Full = "Web_Re_Full.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Web_Re_Hit = "Web_Re_Hit.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Web_Re_Idle = "Web_Re_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Rewards_Box_7Days_Big_Ani = "Rewards_Box_7Days_Big_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_7Days_Big_Appear = "Rewards_Box_7Days_Big_Appear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_7Days_Big_Idle = "Rewards_Box_7Days_Big_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_7Days_Big_Open = "Rewards_Box_7Days_Big_Open.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_7Days_Big_Ready = "Rewards_Box_7Days_Big_Ready.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Rewards_Box_7Days_Small_Ani = "Rewards_Box_7Days_Small_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_7Days_Small_Appear = "Rewards_Box_7Days_Small_Appear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_7Days_Small_Idle = "Rewards_Box_7Days_Small_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_7Days_Small_Open = "Rewards_Box_7Days_Small_Open.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_7Days_Small_Ready = "Rewards_Box_7Days_Small_Ready.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Rewards_Box_LR_Ani = "Rewards_Box_LR_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_LR_Appear = "Rewards_Box_LR_Appear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_LR_Idle = "Rewards_Box_LR_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_LR_Open = "Rewards_Box_LR_Open.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_LR_Ready = "Rewards_Box_LR_Ready.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Rewards_Box_Store_Ani = "Rewards_Box_Store_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_Store_Appear = "Rewards_Box_Store_Appear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_Store_Idle = "Rewards_Box_Store_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_Store_Open = "Rewards_Box_Store_Open.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_Store_Ready = "Rewards_Box_Store_Ready.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string controller_Rewards_Box_WR_Ani = "Rewards_Box_WR_Ani.controller";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_WR_Appear = "Rewards_Box_WR_Appear.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_WR_Idle = "Rewards_Box_WR_Idle.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_WR_Open = "Rewards_Box_WR_Open.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string anim_Rewards_Box_WR_Ready = "Rewards_Box_WR_Ready.anim";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Add = "Add.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Effect_01_Mat = "Effect_01_Mat.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Effect_01_Mat_Add = "Effect_01_Mat_Add.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Effect_02_Mat_Add = "Effect_02_Mat_Add.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Effect_03_Mat = "Effect_03_Mat.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Effect_03_Mat_Add = "Effect_03_Mat_Add.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Effect_Kuai_Mat = "Effect_Kuai_Mat.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FX_Flash_Mat = "FX_Flash_Mat.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FX_Mo_Mat = "FX_Mo_Mat.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FX_Mo_Mat_Add = "FX_Mo_Mat_Add.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FX_Ring_Mat = "FX_Ring_Mat.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FX_Smoke_01_Mat = "FX_Smoke_01_Mat.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FX_Smoke_01_Mat_add = "FX_Smoke_01_Mat_add.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FX_Star_Mat = "FX_Star_Mat.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_Appear_dian2 = "Appear_dian2.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_beijiguang_001 = "beijiguang_001.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_bg1 = "bg1.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_Common_UI_glow_quan = "Common_UI_glow_quan.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_Common_UI_win_congratulations = "Common_UI_win_congratulations.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_daoguang_0012 = "daoguang_0012.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_Effect_glow001 = "Effect_glow001.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_Effect_MaskGlow = "Effect_MaskGlow.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_Effect_Noise001 = "Effect_Noise001.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_Effect_playline = "Effect_playline.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_Effect_playline2 = "Effect_playline2.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_EF_Alpha_Tex = "EF_Alpha_Tex.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_Fang_Tex = "Fang_Tex.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_FX_Tiao = "FX_Tiao.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_glow_Jiao = "glow_Jiao.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_Guangkuang = "Guangkuang.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_HD_Common_UI_Glow = "HD_Common_UI_Glow.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_HD_Common_UI_glow_L = "HD_Common_UI_glow_L.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_HD_Common_UI_glow_Liuguang = "HD_Common_UI_glow_Liuguang.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_HD_Common_UI_glow_Liuguang2 = "HD_Common_UI_glow_Liuguang2.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string jpg_noise = "noise.jpg";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_path_0006 = "path_0006.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_path_0007 = "path_0007.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string PNG_path_0042_1 = "path_0042_1.PNG";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_shandian = "shandian.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_tianguang = "tianguang.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_tianguang1 = "tianguang1.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_tianguang2 = "tianguang2.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_tianguang3 = "tianguang3.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_tianguang4 = "tianguang4.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_Effect_1_Tex = "Effect_1_Tex.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_Effect_2_Tex = "Effect_2_Tex.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_Effect_3_Tex = "Effect_3_Tex.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_Effect_Kuai_Tex = "Effect_Kuai_Tex.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_FX_Flash_Tex = "FX_Flash_Tex.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_FX_Mo_Tex = "FX_Mo_Tex.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_FX_Ring_Tex = "FX_Ring_Tex.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_FX_Smoke_01_Tex = "FX_Smoke_01_Tex.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string png_Hint_2_Tex = "Hint_2_Tex.png";
//Group：PackTogetherByLabel ;Label:#;
     public const string TTF_AMAZON_EMBER_MEDIUM = "AMAZON_EMBER_MEDIUM.TTF";
//Group：PackTogetherByLabel ;Label:#;
     public const string asset_AMAZON_EMBER_MEDIUM_SDF = "AMAZON_EMBER_MEDIUM_SDF.asset";
//Group：PackTogetherByLabel ;Label:#;
     public const string ttf_Edited_AguSans_Black = "Edited_AguSans-Black.ttf";
//Group：PackTogetherByLabel ;Label:#;
     public const string asset_Edited_AguSans_Black_SDF = "Edited_AguSans-Black_SDF.asset";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Blue1 = "Edited_AguSans-Black_SDF_Blue1.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Blue_Btn = "Edited_AguSans-Black_SDF_Blue_Btn.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Blue_Btn_Down = "Edited_AguSans-Black_SDF_Blue_Btn_Down.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Blue_Common_Btn = "Edited_AguSans-Black_SDF_Blue_Common_Btn.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Blue_Common_Btn_Down = "Edited_AguSans-Black_SDF_Blue_Common_Btn_Down.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Blue_Fb_Btn = "Edited_AguSans-Black_SDF_Blue_Fb_Btn.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Blue_Fb_Btn_Down = "Edited_AguSans-Black_SDF_Blue_Fb_Btn_Down.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Brown_OutLine_Big = "Edited_AguSans-Black_SDF_Brown_OutLine_Big.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Brown_Text = "Edited_AguSans-Black_SDF_Brown_Text.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Brown_Title = "Edited_AguSans-Black_SDF_Brown_Title.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Common_Btn = "Edited_AguSans-Black_SDF_Common_Btn.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Common_Btn_down = "Edited_AguSans-Black_SDF_Common_Btn_down.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Common_Btn_gray = "Edited_AguSans-Black_SDF_Common_Btn_gray.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Common_Btn_Small = "Edited_AguSans-Black_SDF_Common_Btn_Small.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Common_Btn_Volet = "Edited_AguSans-Black_SDF_Common_Btn_Volet.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Common_Not_Outline = "Edited_AguSans-Black_SDF_Common_Not_Outline.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Common_Title_Underlay_Gray = "Edited_AguSans-Black_SDF_Common_Title_Underlay_Gray.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_DailyWheelBlock = "Edited_AguSans-Black_SDF_DailyWheelBlock.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Dark_Brown_Text = "Edited_AguSans-Black_SDF_Dark_Brown_Text.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Dark_Green = "Edited_AguSans-Black_SDF_Dark_Green.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Disable_Text = "Edited_AguSans-Black_SDF_Disable_Text.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Disable_Thick_Line = "Edited_AguSans-Black_SDF_Disable_Thick_Line.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Email_Red_OU = "Edited_AguSans-Black_SDF_Email_Red_OU.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Gray3 = "Edited_AguSans-Black_SDF_Gray3.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Gray_2 = "Edited_AguSans-Black_SDF_Gray_2.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Gray_Btn = "Edited_AguSans-Black_SDF_Gray_Btn.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Gray_Outline = "Edited_AguSans-Black_SDF_Gray_Outline.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Gray_Title = "Edited_AguSans-Black_SDF_Gray_Title.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Green1 = "Edited_AguSans-Black_SDF_Green1.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Home_Loading = "Edited_AguSans-Black_SDF_Home_Loading.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Normal = "Edited_AguSans-Black_SDF_Normal.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Photo_Disable_Title = "Edited_AguSans-Black_SDF_Photo_Disable_Title.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Photo_Title = "Edited_AguSans-Black_SDF_Photo_Title.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Red_Btn = "Edited_AguSans-Black_SDF_Red_Btn.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Red_Btn_Down = "Edited_AguSans-Black_SDF_Red_Btn_Down.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Red_Thick_Line = "Edited_AguSans-Black_SDF_Red_Thick_Line.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Restore = "Edited_AguSans-Black_SDF_Restore.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Shop_Brown_Text = "Edited_AguSans-Black_SDF_Shop_Brown_Text.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Shop_Title_Text = "Edited_AguSans-Black_SDF_Shop_Title_Text.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Title_SDF = "Edited_AguSans-Black_SDF_Title_SDF.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Volet_Text = "Edited_AguSans-Black_SDF_Volet_Text.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Window_Title = "Edited_AguSans-Black_SDF_Window_Title.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_Edited_AguSans_Black_SDF_Yellow = "Edited_AguSans-Black_SDF_Yellow.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string asset_FREDOKAONE_REGULAR = "FREDOKAONE_REGULAR.asset";
//Group：PackTogetherByLabel ;Label:#;
     public const string TTF_FREDOKAONE_REGULAR = "FREDOKAONE_REGULAR.TTF";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FREDOKAONE_REGULAR_Blue_Btn = "FREDOKAONE_REGULAR_Blue_Btn.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FREDOKAONE_REGULAR_Blue_Outline = "FREDOKAONE_REGULAR_Blue_Outline.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FREDOKAONE_REGULAR_ComingSoon = "FREDOKAONE_REGULAR_ComingSoon.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FREDOKAONE_REGULAR_Common_White = "FREDOKAONE_REGULAR_Common_White.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FREDOKAONE_REGULAR_Deep_Blue = "FREDOKAONE_REGULAR_Deep_Blue.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FREDOKAONE_REGULAR_Deep_Gray = "FREDOKAONE_REGULAR_Deep_Gray.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FREDOKAONE_REGULAR_Gray_Outline = "FREDOKAONE_REGULAR_Gray_Outline.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FREDOKAONE_REGULAR_Gray_Outline_Shadow = "FREDOKAONE_REGULAR_Gray_Outline_Shadow.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FREDOKAONE_REGULAR_Green_Btn = "FREDOKAONE_REGULAR_Green_Btn.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FREDOKAONE_REGULAR_Num_Red = "FREDOKAONE_REGULAR_Num_Red.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FREDOKAONE_REGULAR_Orange_Btn = "FREDOKAONE_REGULAR_Orange_Btn.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FREDOKAONE_REGULAR_Red_Btn = "FREDOKAONE_REGULAR_Red_Btn.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FREDOKAONE_REGULAR_Title = "FREDOKAONE_REGULAR_Title.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FREDOKAONE_REGULAR_Vollet = "FREDOKAONE_REGULAR_Vollet.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string mat_FREDOKAONE_REGULAR_Yellowish_Brown = "FREDOKAONE_REGULAR_Yellowish_Brown.mat";
//Group：PackTogetherByLabel ;Label:#;
     public const string ttf_Helvetica_Black_SemiBold_1 = "Helvetica-Black-SemiBold_1.ttf";
//Group：PackTogetherByLabel ;Label:#;
     public const string ttf_LiberationSans = "LiberationSans.ttf";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_0 = "championships_head_0.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_1 = "championships_head_1.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_10 = "championships_head_10.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_11 = "championships_head_11.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_12 = "championships_head_12.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_13 = "championships_head_13.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_14 = "championships_head_14.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_15 = "championships_head_15.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_16 = "championships_head_16.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_17 = "championships_head_17.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_18 = "championships_head_18.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_19 = "championships_head_19.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_2 = "championships_head_2.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_20 = "championships_head_20.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_3 = "championships_head_3.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_4 = "championships_head_4.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_5 = "championships_head_5.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_6 = "championships_head_6.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_7 = "championships_head_7.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_8 = "championships_head_8.png";
//Group：PackSeparately ;Label:HeadIcon;
     public const string png_championships_head_9 = "championships_head_9.png";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Card_108072020_2 = "Android_Card_108072020_2.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Card_108072020_4 = "Android_Card_108072020_4.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Card_108072020_6 = "Android_Card_108072020_6.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Card_208072020_2 = "Android_Card_208072020_2.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Card_208072020_4 = "Android_Card_208072020_4.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Card_208072020_6 = "Android_Card_208072020_6.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Level_1 = "Android_Level_1.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Level_2 = "Android_Level_2.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Level_2000001 = "Android_Level_2000001.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Level_2000002 = "Android_Level_2000002.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Level_2000003 = "Android_Level_2000003.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Level_2000004 = "Android_Level_2000004.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Level_2000005 = "Android_Level_2000005.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Level_2000006 = "Android_Level_2000006.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Level_3 = "Android_Level_3.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Level_4 = "Android_Level_4.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Level_5 = "Android_Level_5.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Android_Level_6 = "Android_Level_6.txt";
//Group：LocalLevel ;Label:levels;
     public const string jpg_cheese_1 = "cheese_1.jpg";
//Group：LocalLevel ;Label:levels;
     public const string jpg_coconuts_1 = "coconuts_1.jpg";
//Group：LocalLevel ;Label:levels;
     public const string jpg_comb_1 = "comb_1.jpg";
//Group：LocalLevel ;Label:levels;
     public const string jpg_dream_1 = "dream_1.jpg";
//Group：LocalLevel ;Label:levels;
     public const string jpg_hippo_1 = "hippo_1.jpg";
//Group：LocalLevel ;Label:levels;
     public const string txt_Ios_Card_08062020_2 = "Ios_Card_08062020_2.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Ios_Card_08062020_4 = "Ios_Card_08062020_4.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Ios_Card_08062020_6 = "Ios_Card_08062020_6.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Ios_Level_1 = "Ios_Level_1.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Ios_Level_2 = "Ios_Level_2.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Ios_Level_3 = "Ios_Level_3.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Ios_Level_4 = "Ios_Level_4.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Ios_Level_5 = "Ios_Level_5.txt";
//Group：LocalLevel ;Label:levels;
     public const string txt_Ios_Level_6 = "Ios_Level_6.txt";
//Group：LocalLevel ;Label:levels;
     public const string jpg_journey_1 = "journey_1.jpg";
//Group：LocalLevel ;Label:levels;
     public const string jpg_plane_1 = "plane_1.jpg";
//Group：LocalLevel ;Label:levels;
     public const string jpg_water_1 = "water_1.jpg";
//Group：LocalLevel ;Label:levels;
     public const string jpg_wrongfoot_1 = "wrongfoot_1.jpg";
//Group：LocalLevel ;Label:levels;
     public const string jpg_yoyo_1 = "yoyo_1.jpg";
}