_G.t_ad = {
     [1] = {
          ['id'] = 1,
          ['AdUnlock'] = 1,
          ['AdType'] = "1.0",
          ['Push'] = {0},
          ['AdName'] = "回到主界面",
          ['AdTeam'] = 1,
          ['AdCD'] = 60,
          ['ADMax'] = 5,
          ['AdReset'] = 1,
          },

     [2] = {
          ['id'] = 2,
          ['AdUnlock'] = 1,
          ['AdType'] = "1.0",
          ['Push'] = {0},
          ['AdName'] = "点击进入游戏",
          ['AdTeam'] = 1,
          ['AdCD'] = 60,
          ['ADMax'] = 5,
          ['AdReset'] = 1,
          },

     [3] = {
          ['id'] = 3,
          ['AdUnlock'] = 1,
          ['AdType'] = "1.0",
          ['Push'] = {0},
          ['AdName'] = "点击下一关",
          ['AdTeam'] = 1,
          ['AdCD'] = 60,
          ['ADMax'] = 5,
          ['AdReset'] = 1,
          },

     [4] = {
          ['id'] = 4,
          ['AdUnlock'] = 1,
          ['AdType'] = "1.0",
          ['Push'] = {0},
          ['AdName'] = "点击重新开始",
          ['AdTeam'] = 2,
          ['AdCD'] = 20,
          ['ADMax'] = 10,
          ['AdReset'] = 1,
          },

     [5] = {
          ['id'] = 5,
          ['AdUnlock'] = 1,
          ['AdType'] = "2.0",
          ['Push'] = {0},
          ['AdName'] = "商城-免费抽奖",
          ['AdTeam'] = 3,
          ['AdCD'] = 120,
          ['ADMax'] = 10,
          ['AdReset'] = 0,
          },

     [6] = {
          ['id'] = 6,
          ['AdUnlock'] = 1,
          ['AdType'] = "2.0",
          ['Push'] = {0},
          ['AdName'] = "商城-免费金币",
          ['AdTeam'] = 4,
          ['AdCD'] = 120,
          ['ADMax'] = 10,
          ['AdReset'] = 0,
          },

     [7] = {
          ['id'] = 7,
          ['AdUnlock'] = 1,
          ['AdType'] = "2.0",
          ['Push'] = {0},
          ['AdName'] = "商城-免费道具",
          ['AdTeam'] = 5,
          ['AdCD'] = 30,
          ['ADMax'] = 5,
          ['AdReset'] = 0,
          },

     [8] = {
          ['id'] = 8,
          ['AdUnlock'] = 1,
          ['AdType'] = "2.0",
          ['Push'] = {0},
          ['AdName'] = "免费金币提示窗",
          ['AdTeam'] = 6,
          ['AdCD'] = 30,
          ['ADMax'] = 5,
          ['AdReset'] = 0,
          },

     [9] = {
          ['id'] = 9,
          ['AdUnlock'] = 1,
          ['AdType'] = "2.0",
          ['Push'] = {0},
          ['AdName'] = "主界面漂浮物",
          ['AdTeam'] = 7,
          ['AdCD'] = 30,
          ['ADMax'] = 5,
          ['AdReset'] = 0,
          },

     [10] = {
          ['id'] = 10,
          ['AdUnlock'] = 1,
          ['AdType'] = "2.0",
          ['Push'] = {0},
          ['AdName'] = "进入游戏推送礼包",
          ['AdTeam'] = 8,
          ['AdCD'] = 30,
          ['ADMax'] = 5,
          ['AdReset'] = 0,
          },

     [11] = {
          ['id'] = 11,
          ['AdUnlock'] = 1,
          ['AdType'] = "2.0",
          ['Push'] = {0},
          ['AdName'] = "游戏中推送礼包",
          ['AdTeam'] = 9,
          ['AdCD'] = 30,
          ['ADMax'] = 5,
          ['AdReset'] = 0,
          },

     [12] = {
          ['id'] = 12,
          ['AdUnlock'] = 1,
          ['AdType'] = "2.0",
          ['Push'] = {0},
          ['AdName'] = "开局前推送道具",
          ['AdTeam'] = 10,
          ['AdCD'] = 30,
          ['ADMax'] = 5,
          ['AdReset'] = 0,
          },

     [13] = {
          ['id'] = 13,
          ['AdUnlock'] = 1,
          ['AdType'] = "2.0",
          ['Push'] = {0},
          ['AdName'] = "复活广告加步数",
          ['AdTeam'] = 11,
          ['AdCD'] = 30,
          ['ADMax'] = 5,
          ['AdReset'] = 0,
          },

     [14] = {
          ['id'] = 14,
          ['AdUnlock'] = 1,
          ['AdType'] = "2.0",
          ['Push'] = {0},
          ['AdName'] = "过关奖励-形式1",
          ['AdTeam'] = 12,
          ['AdCD'] = 30,
          ['ADMax'] = 5,
          ['AdReset'] = 0,
          },

     [15] = {
          ['id'] = 15,
          ['AdUnlock'] = 1,
          ['AdType'] = "2.0",
          ['Push'] = {0},
          ['AdName'] = "过关奖励-形式2",
          ['AdTeam'] = 13,
          ['AdCD'] = 30,
          ['ADMax'] = 5,
          ['AdReset'] = 0,
          },

     [16] = {
          ['id'] = 16,
          ['AdUnlock'] = 1,
          ['AdType'] = "2.0",
          ['Push'] = {0},
          ['AdName'] = "过关奖励-形式3",
          ['AdTeam'] = 14,
          ['AdCD'] = 30,
          ['ADMax'] = 5,
          ['AdReset'] = 0,
          },

     [17] = {
          ['id'] = 17,
          ['AdUnlock'] = 1,
          ['AdType'] = "2.0",
          ['Push'] = {0},
          ['AdName'] = "过关奖励-形式4",
          ['AdTeam'] = 15,
          ['AdCD'] = 30,
          ['ADMax'] = 5,
          ['AdReset'] = 0,
          },

     [18] = {
          ['id'] = 18,
          ['AdUnlock'] = 1,
          ['AdType'] = "2.0",
          ['Push'] = {0},
          ['AdName'] = "过关奖励-形式5",
          ['AdTeam'] = 16,
          ['AdCD'] = 30,
          ['ADMax'] = 5,
          ['AdReset'] = 0,
          },

     [19] = {
          ['id'] = 19,
          ['AdUnlock'] = 1,
          ['AdType'] = "2.0",
          ['Push'] = {0},
          ['AdName'] = "补签",
          ['AdTeam'] = 17,
          ['AdCD'] = 30,
          ['ADMax'] = 5,
          ['AdReset'] = 0,
          },

     [20] = {
          ['id'] = 20,
          ['AdUnlock'] = 1,
          ['AdType'] = "2.0",
          ['Push'] = {0},
          ['AdName'] = "高级签到奖励",
          ['AdTeam'] = 18,
          ['AdCD'] = 30,
          ['ADMax'] = 5,
          ['AdReset'] = 0,
          },

}