_G.t_specialele = {
     [1] = {
          ['id'] = 1,
          ['Layer'] = 2,
          ['canDispel'] = true,
          ['actionType'] = 0,
          ['dispeldown'] = true,
          ['isLogicDispelJudge'] = true,
          ['isAffectedHammer'] = true,
          ['isObstructFaller'] = true,
          ['maxDispelCount'] = 1,
          ['actionIntervalStep'] = 0,
          ['prefabName'] = "Block-yellow",
          ['prefabName_ui'] = "Block-yellow",
          },

     [2] = {
          ['id'] = 2,
          ['Layer'] = 2,
          ['canDispel'] = true,
          ['actionType'] = 0,
          ['dispeldown'] = true,
          ['isLogicDispelJudge'] = true,
          ['isAffectedHammer'] = true,
          ['isObstructFaller'] = true,
          ['maxDispelCount'] = 1,
          ['actionIntervalStep'] = 0,
          ['prefabName'] = "Block-yellow",
          ['prefabName_ui'] = "Block-yellow",
          },

     [3] = {
          ['id'] = 3,
          ['Layer'] = 2,
          ['canDispel'] = true,
          ['actionType'] = 0,
          ['dispeldown'] = true,
          ['isLogicDispelJudge'] = true,
          ['isAffectedHammer'] = true,
          ['isObstructFaller'] = true,
          ['maxDispelCount'] = 1,
          ['actionIntervalStep'] = 0,
          ['prefabName'] = "Block-yellow",
          ['prefabName_ui'] = "Block-yellow",
          },

     [4] = {
          ['id'] = 4,
          ['Layer'] = 2,
          ['canDispel'] = true,
          ['actionType'] = 0,
          ['dispeldown'] = true,
          ['isLogicDispelJudge'] = true,
          ['isAffectedHammer'] = true,
          ['isObstructFaller'] = true,
          ['maxDispelCount'] = 1,
          ['actionIntervalStep'] = 0,
          ['prefabName'] = "Block-yellow",
          ['prefabName_ui'] = "Block-yellow",
          },

     [5] = {
          ['id'] = 5,
          ['Layer'] = 1,
          ['canDispel'] = false,
          ['actionType'] = 0,
          ['dispeldown'] = false,
          ['isLogicDispelJudge'] = false,
          ['isAffectedHammer'] = false,
          ['isObstructFaller'] = false,
          ['maxDispelCount'] = 0,
          ['actionIntervalStep'] = 3,
          ['prefabName'] = "Block-belt",
          ['prefabName_ui'] = "Block-belt",
          },

     [6] = {
          ['id'] = 6,
          ['Layer'] = 2,
          ['canDispel'] = true,
          ['actionType'] = 1,
          ['dispeldown'] = true,
          ['isLogicDispelJudge'] = true,
          ['isAffectedHammer'] = true,
          ['isObstructFaller'] = true,
          ['maxDispelCount'] = 1,
          ['actionIntervalStep'] = 0,
          ['prefabName'] = "Block-neon",
          ['prefabName_ui'] = "Block-neon",
          },

     [7] = {
          ['id'] = 7,
          ['Layer'] = 2,
          ['canDispel'] = false,
          ['actionType'] = 0,
          ['dispeldown'] = true,
          ['isLogicDispelJudge'] = true,
          ['isAffectedHammer'] = false,
          ['isObstructFaller'] = true,
          ['maxDispelCount'] = 0,
          ['actionIntervalStep'] = 1,
          ['prefabName'] = "Block-hat",
          ['prefabName_ui'] = "Block-hat",
          },

     [8] = {
          ['id'] = 8,
          ['Layer'] = 3,
          ['canDispel'] = true,
          ['actionType'] = 0,
          ['dispeldown'] = false,
          ['isLogicDispelJudge'] = true,
          ['isAffectedHammer'] = true,
          ['isObstructFaller'] = true,
          ['maxDispelCount'] = 1,
          ['actionIntervalStep'] = 0,
          ['prefabName'] = "Block-star",
          ['prefabName_ui'] = "Block-star",
          },

     [9] = {
          ['id'] = 9,
          ['Layer'] = 5,
          ['canDispel'] = true,
          ['actionType'] = 0,
          ['dispeldown'] = true,
          ['isLogicDispelJudge'] = true,
          ['isAffectedHammer'] = true,
          ['isObstructFaller'] = true,
          ['maxDispelCount'] = 1,
          ['actionIntervalStep'] = 2,
          ['prefabName'] = "Block-foam",
          ['prefabName_ui'] = "Block-foam",
          },

     [10] = {
          ['id'] = 10,
          ['Layer'] = 5,
          ['canDispel'] = true,
          ['actionType'] = 0,
          ['dispeldown'] = true,
          ['isLogicDispelJudge'] = true,
          ['isAffectedHammer'] = true,
          ['isObstructFaller'] = true,
          ['maxDispelCount'] = 2,
          ['actionIntervalStep'] = 0,
          ['prefabName'] = "Block-rope",
          ['prefabName_ui'] = "Block-rope",
          },

     [11] = {
          ['id'] = 11,
          ['Layer'] = 3,
          ['canDispel'] = true,
          ['actionType'] = 0,
          ['dispeldown'] = false,
          ['isLogicDispelJudge'] = true,
          ['isAffectedHammer'] = true,
          ['isObstructFaller'] = true,
          ['maxDispelCount'] = 1,
          ['actionIntervalStep'] = 3,
          ['prefabName'] = "Block-butterfly",
          ['prefabName_ui'] = "Block-butterfly",
          },

     [12] = {
          ['id'] = 12,
          ['Layer'] = 3,
          ['canDispel'] = true,
          ['actionType'] = 0,
          ['dispeldown'] = false,
          ['isLogicDispelJudge'] = true,
          ['isAffectedHammer'] = true,
          ['isObstructFaller'] = true,
          ['maxDispelCount'] = 1,
          ['actionIntervalStep'] = 0,
          ['prefabName'] = "Block-lightning",
          ['prefabName_ui'] = "Block-lightning",
          },

     [13] = {
          ['id'] = 13,
          ['Layer'] = 2,
          ['canDispel'] = true,
          ['actionType'] = 0,
          ['dispeldown'] = false,
          ['isLogicDispelJudge'] = true,
          ['isAffectedHammer'] = true,
          ['isObstructFaller'] = true,
          ['maxDispelCount'] = 1,
          ['actionIntervalStep'] = 0,
          ['prefabName'] = "Block-dice",
          ['prefabName_ui'] = "Block-dice",
          },

     [14] = {
          ['id'] = 14,
          ['Layer'] = 2,
          ['canDispel'] = false,
          ['actionType'] = 0,
          ['dispeldown'] = false,
          ['isLogicDispelJudge'] = true,
          ['isAffectedHammer'] = false,
          ['isObstructFaller'] = true,
          ['maxDispelCount'] = 0,
          ['actionIntervalStep'] = 0,
          ['prefabName'] = "Block-steel",
          ['prefabName_ui'] = "Block-steel",
          },

     [15] = {
          ['id'] = 15,
          ['Layer'] = 2,
          ['canDispel'] = false,
          ['actionType'] = 0,
          ['dispeldown'] = false,
          ['isLogicDispelJudge'] = false,
          ['isAffectedHammer'] = false,
          ['isObstructFaller'] = true,
          ['maxDispelCount'] = 1,
          ['actionIntervalStep'] = 0,
          ['prefabName'] = "Block-obstacle",
          ['prefabName_ui'] = "Block-obstacle",
          },

     [16] = {
          ['id'] = 16,
          ['Layer'] = 4,
          ['canDispel'] = true,
          ['actionType'] = 0,
          ['dispeldown'] = false,
          ['isLogicDispelJudge'] = false,
          ['isAffectedHammer'] = false,
          ['isObstructFaller'] = false,
          ['maxDispelCount'] = 1,
          ['actionIntervalStep'] = 0,
          ['prefabName'] = "Block-bubble",
          ['prefabName_ui'] = "Block-bubble",
          },

     [17] = {
          ['id'] = 17,
          ['Layer'] = 2,
          ['canDispel'] = false,
          ['actionType'] = 0,
          ['dispeldown'] = false,
          ['isLogicDispelJudge'] = false,
          ['isAffectedHammer'] = true,
          ['isObstructFaller'] = true,
          ['maxDispelCount'] = 0,
          ['actionIntervalStep'] = 0,
          ['prefabName'] = "Block-faller",
          ['prefabName_ui'] = "Block-faller",
          },

     [18] = {
          ['id'] = 18,
          ['Layer'] = 2,
          ['canDispel'] = true,
          ['actionType'] = 1,
          ['dispeldown'] = true,
          ['isLogicDispelJudge'] = true,
          ['isAffectedHammer'] = true,
          ['isObstructFaller'] = true,
          ['maxDispelCount'] = 1,
          ['actionIntervalStep'] = 0,
          ['prefabName'] = "Block-coin",
          ['prefabName_ui'] = "Block-coin",
          },

     [101] = {
          ['id'] = 101,
          ['Layer'] = 2,
          ['canDispel'] = true,
          ['actionType'] = 0,
          ['dispeldown'] = false,
          ['isLogicDispelJudge'] = true,
          ['isAffectedHammer'] = true,
          ['isObstructFaller'] = true,
          ['maxDispelCount'] = 1,
          ['actionIntervalStep'] = 0,
          ['prefabName'] = "Block-rainbow",
          ['prefabName_ui'] = "Block-rainbow",
          },

}