package com.imop.lj.gameserver.overman.msg;

import java.util.HashMap;
import java.util.Map;

import com.imop.lj.core.msg.MessageType;
import com.imop.lj.common.MessageMappingProvider;

/**
 *  Generated by MessageCodeGenerator,don't modify please.
 *  Need to register in<code>GameMessageRecognizer#init</code>
 */
public class OvermanMsgMappingProvider implements MessageMappingProvider {

	@Override
	public Map<Short, Class<?>> getMessageMapping() {
		Map<Short, Class<?>> map = new HashMap<Short, Class<?>>();
		map.put(MessageType.CG_FIRST_OVERMAN, CGFirstOverman.class);
		map.put(MessageType.CG_OVERMAN, CGOverman.class);
		map.put(MessageType.CG_OVERMAN_INFO, CGOvermanInfo.class);
		map.put(MessageType.CG_FIRST_FIRE_OVERMAN, CGFirstFireOverman.class);
		map.put(MessageType.CG_FIRE_OVERMAN, CGFireOverman.class);
		map.put(MessageType.CG_FIRST_TEAM_FIRE_OVERMAN, CGFirstTeamFireOverman.class);
		map.put(MessageType.CG_TEAM_FIRE_OVERMAN, CGTeamFireOverman.class);
		map.put(MessageType.CG_FORCE_FIRE_OVERMAN, CGForceFireOverman.class);
		map.put(MessageType.CG_GET_OVERMAN_REWARD, CGGetOvermanReward.class);
		map.put(MessageType.CG_GET_LOWERMAN_REWARD, CGGetLowermanReward.class);
		map.put(MessageType.CG_ADD_LOWERMAN_REWARD, CGAddLowermanReward.class);
		map.put(MessageType.CG_ADD_OVERMAN_REWARD, CGAddOvermanReward.class);
		return map;
	}

}
