// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Excel Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;
using BetaFramework;
public class IosAdsConfigData : TableSOBaseData<string>
{
    //分层名称
    public string BusinessKey;

    //商店激励视频是否打开
    public bool S_RV_IsShown;

    //商店激励视频从哪关开启
    public int S_RV_BeginLevel;

    //商店激励视频奖励的金币数
    public int S_RV_RewardCoin;

    //关卡内激励视频奖励的hint数
    public bool S_RV_RewardHint;

    //商店激励视频间隔时间
    public int S_RV_CD;

    //主关卡内激励视频是否打开
    public bool GP_RV_IsShown;

    //关卡内激励视频从哪关开启
    public int GP_RV_BeginLevel;

    //关卡内激励视频奖励的金币数
    public int GP_RV_RewardCoin;

    //关卡内激励视频奖励的hint数
    public bool GP_RV_RewardHint;

    //关卡内激励视频间隔时间
    public int GP_RV_CD;

    //所有激励视频每天最大次数
    public int RV_MaxCount;

    //插屏打开几次商店后出现
    public int IN_ShopOpenTimes;

    //插屏广告间隔时间
    public int IN_CD;

    //插屏从第一次从第几关出现
    public int IN_BegainLevel;

    //插屏广告间每天最大次数
    public int IN_MaxCount;

    //锦标赛期间插屏广告间每天最大次数
    public int WK_IN_MaxCount;

    //锦标赛期间插屏广告间隔时间
    public int WK_IN_CD;

    //锦标赛期间激励视频每天最大次数
    public int WK_RV_MaxCount;

    //banner开始关卡
    public int BANNER_BeginLevel;

}
