// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Excel Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using BetaFramework;

public class RateConfigData : TableSOBaseData<int>
{
    //key
    public int ID;

    //评价系统是否开启
    public bool IsShown;

    // 第一次弹出评价关卡
    public int FirstBeginLevel;

    //第二次弹出评价关卡
    public int SecondBeginLevel;

    //是否开启过滤评价
    public bool IsFilterComment;

    //评价赠给玩家金币数
    public int RewardCoin;
}